### ISSUE TITLE
Accept a GeometrySequence object as input for GeoDataFrame geometry

### ISSUE THREAD

**Issue by mjpieters** [geopandas/geopandas#1037]
A Shapely `GeometrySequence()` instance should be acceptable as input for the `geometry` argument to `GeoDataFrame()`, as it represents an ordered sequence of points, and `GeoSeries()` already accepts the type.

E.g., starting with a numpy array of longitude and latitude values, creating a `MultiPoint()` object is as simple as using `asMultiPoint()`, which is also extremely efficient as it simply shares the array:

```python
import numpy as np
import geopandas as gpd
from shapely.geometry import asMultiPoint

coords = np.stack(
    (
        (np.random.random(1000) * 360) - 180,
        (np.random.random(1000) * 180) - 90
    ),
    axis=1
)
points = asMultiPoint(coords)
```

I can create a `GeoSeries()` from this by using the `.geoms` attribute, which gives me a `GeometrySequence()` instance:

```python
print(type(points), type(points.geoms), sep="\n")
# <class 'shapely.geometry.multipoint.MultiPointAdapter'>
# <class 'shapely.geometry.base.GeometrySequence'>
series = gpd.GeoSeries(points.geoms)

# The series contains the same points
print(len(gpd.GeoSeries(points.geoms)) == coords.shape[0])
# True
print(all(sp == pp for sp, pp in zip(series, points)))
# True
```

but I can't pass the `GeometrySequence` object directly to `GeometryDataFrame()` as the `geometry` attribute:

```python
gpd.GeoDataFrame(geometry=points.geoms)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/geopandas/geodataframe.py", line 50, in __init__
    self.set_geometry(geometry, inplace=True)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/geopandas/geodataframe.py", line 128, in set_geometry
    level = frame[col].values
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/geopandas/geodataframe.py", line 471, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1142, in _get_listlike_indexer
    kind=self.name)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2981, in _convert_listlike_indexer
    keyarr = self._convert_arr_indexer(keyarr)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3001, in _convert_arr_indexer
    keyarr = com.asarray_tuplesafe(keyarr)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/pandas/core/common.py", line 232, in asarray_tuplesafe
    result = np.asarray(values, dtype=dtype)
  File "/Users/mj/Development/venvs/stackoverflow-3.7/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'Point'
```

The work-around right now is to either convert the `GeometrySequence()` instance to a list first (`geometry=list(points.geoms)`, can be shortened to `geometry=list(points)`), or to create a `GeoSeries()` object from the `GeometrySequence` object:

```python
gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(points.geoms))
```

**Comment by mjpieters** [comment]
Side note: it appears that `geometry=list(points)` is faster than `geometry(gpd.GeoSeries(points.geoms))`:

| input size | `list(points)` | `geometry(gpd.GeoSeries(points.geoms))` |
| ---------: | ------------- | ----------------|
| 1000       | 6 ms              | 35 ms                 |
| 10.000    | 35 ms            | 300ms                |
| 100.000 | 343 ms           | 3.3 s                   |
