### ISSUE TITLE
BUG: _validate_geometry_data raising error for Series with list-like data

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1047]
From the doc build:

```
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/geopandas/checkouts/latest/examples/plotting_with_geoplot.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/checkouts/latest/examples/plotting_with_geoplot.py", line 80, in <module>
    linewidth=0)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/geoplot/geoplot.py", line 2134, in voronoi
    geoms = _build_voronoi_polygons(df)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/geoplot/geoplot.py", line 2636, in _build_voronoi_polygons
    geom = np.array(df.geometry.map(lambda p: [p.x, p.y]).tolist())
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/pandas/core/series.py", line 3384, in map
    index=self.index).__finalize__(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/geopandas/geoseries.py", line 90, in __new__
    _validate_geometry_data(s.values)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/geopandas/geoseries.py", line 29, in _validate_geometry_data
    if not all(isinstance(item, BaseGeometry) or pd.isna(item) for item in data):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I don't see it locally anymore with the latest geoplot, so it might be not present anymore there, but still, this seems a bug in geopandas we should try to fix.

**Comment by jorisvandenbossche** [comment]
Ah, the usage of `_validate_geometry_data` has been fixed in https://github.com/geopandas/geopandas/pull/835 by using `from_shapely`, which handles this case fine. Probably good to add a test though.
