### ISSUE TITLE
API: align with pandas DataFrame/Sereis.explode ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1140]
Pandas added an `explode` method in 0.25.0 (see eg https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.explode.html).

This has basically the same functionality (so that is good, no big conflict!), but with some small differences:

- The DataFrame version has a `column` keyword to indicate which column to explode
- They don't return a MultiIndex but only the original, repeated index

We could add such a `column` keyword to `GeoDataFrame.explode` and if that is specified for a column different than the geometry column, use to the DataFrame implementation (so the new pandas functionality also becomes available on the GeoDataFrame, as that is now masked by our override). 

For the original index vs multi-index, I am less sure (I think there is some value in also being able to have the MultiIndex if you want that). Maybe we could add an option to have this or not, so at least you can have the same behaviour as the pandas version.

**Comment by martinfleis** [comment]
> We could add such a column keyword to GeoDataFrame.explode and if that is specified for a column different than the geometry column, use to the DataFrame implementation

That makes sense. 

> For the original index vs multi-index, I am less sure

Me too. Having Multiindex feels more sophisticated than repeated index, but I am thinking what is better, whether to have the same behaviour as pandas or to offer Multiindex by default. We should add an option, but I am quite unsure which of the options should be default.

**Comment by iboates** [comment]
I'm trying to fix this but when I try to call `GeoDataFrame`'s parent class, it complains about having too many arguments, despite the fact that it is literally the exact same as the implementation for `.astype()` further down. ???

While in the `.explode()` method context (I added `column, **args` to the method params:

```
>>> super(GeoDataFrame, self).explode(column)
Traceback (most recent call last):
  File "/home/isaek/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: explode() takes 1 positional argument but 2 were given
```

But in the override for `.astype()`:

```
>>> super(GeoDataFrame, self).astype(dtype, copy=copy, errors=errors, **kwargs)
```

This works fine apparently (I didn't touch this method)
