### ISSUE TITLE
DOC/COMPAT: xml parse error from cartopy in the doc build

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1267]
I see 

```
generating gallery for gallery... [100%] cartopy_convert.py
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/geopandas/checkouts/latest/examples/cartopy_convert.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/checkouts/latest/examples/cartopy_convert.py", line 58, in <module>
    crs_epsg = ccrs.epsg('3857')
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/cartopy/crs.py", line 2540, in epsg
    return cartopy._epsg._EPSGProjection(code)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/cartopy/_epsg.py", line 69, in __init__
    x0, x1, y0, y1 = projection.domain_of_validity()
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/pyepsg.py", line 205, in domain_of_validity
    gml = ET.fromstring(xml)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 4
```

**Comment by jorisvandenbossche** [comment]
See https://github.com/SciTools/cartopy/issues/1444 and https://github.com/maptiler/epsg.io/issues/156, should be fixed (let's check on readthedocs after the next build)

**Comment by martinfleis** [comment]
Seems to be resolved.
