### ISSUE TITLE
Jupyter kernel dies when importing fiona before geopandas

### ISSUE THREAD

**Issue by vishalmhjn** [geopandas/geopandas#1418]
I found out that importing fiona before geopandas kill the kernel in Jupyter Notebook
Python 3.7 (virtualenv) OSX 10.15.4

import fiona
import geopandas as gpd
shapefile = gpd.read_file('shapefile.shp')

But works fine when fiona is imported after geopandas

**Comment by martinfleis** [comment]
How did you install Fiona and geopandas? When does it kill the kernel, on import or on `read_file`? I guess that is some kind of conflict of C dependencies.

**Comment by vishalmhjn** [comment]
I think I installed both of them using pip. 
Fiona                                   1.8.13
geopandas                         0.6.2 

It crashes on read_file.
Error:
`python3(16790,0x105419dc0) malloc: *** error for object 0x10502e8d0: pointer being freed was not allocated
python3(16790,0x105419dc0) malloc: *** set a breakpoint in malloc_error_break to debug`

**Comment by martinfleis** [comment]
The error comes from C, so there is likely some issue with GDAL. Multiple installations, installations from different sources, something like that. These kinds of conflicts happen and are usually resolved by reinstalling dependencies from a single source (optimally conda-forge). It is strange that it depends on the order of imports though.

**Comment by vishalmhjn** [comment]
checked the error in ipython too...it does happen due to the order of imports.

**Comment by srenoes** [comment]
i had some similar issue when copying testing code into a command line ... in that case also other libs before geopandas, which gave errors that could not be recovered from.

If I, however, first imported geopandas and then other libs it worked fine. In a venv. Ill check the  stuff and add some code here to give more information

**Comment by srenoes** [comment]
To reproduce I activated my venv, then python and entered following commands:
```python
import json
import os
import shutil
import tempfile

import numpy as np
import pandas as pd

import fiona
from pyproj.exceptions import CRSError
from shapely.geometry import Point

import geopandas
from geopandas import GeoDataFrame, GeoSeries, read_file
from geopandas.array import GeometryArray, GeometryDtype, from_shapely

from geopandas.testing import assert_geodataframe_equal, assert_geoseries_equal
from geopandas.tests.util import PACKAGE_DIR, validate_boro_df
from pandas.testing import assert_frame_equal, assert_index_equal, assert_series_equal
import pytest
```
errors I got:
import geopandas
Traceback (most recent call last):
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 65, in set_use_pygeos
    import pygeos  # noqa
  File "D:\shortcut\HSL\venv\lib\site-packages\pygeos\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 102, in <module>
    set_use_pygeos()
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 96, in set_use_pygeos
    raise ImportError(
ImportError: To use the PyGEOS speed-ups within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install 
pygeos'
>>> from geopandas import GeoDataFrame, GeoSeries, read_file
Traceback (most recent call last):
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 65, in set_use_pygeos
    import pygeos  # noqa
  File "D:\shortcut\HSL\venv\lib\site-packages\pygeos\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 102, in <module>
    set_use_pygeos()
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 96, in set_use_pygeos
    raise ImportError(
ImportError: To use the PyGEOS speed-ups within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install 
pygeos'
>>> from geopandas.array import GeometryArray, GeometryDtype, from_shapely
Traceback (most recent call last):
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 65, in set_use_pygeos
    import pygeos  # noqa
  File "D:\shortcut\HSL\venv\lib\site-packages\pygeos\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 102, in <module>
    set_use_pygeos()
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\_compat.py", line 96, in set_use_pygeos
    raise ImportError(
ImportError: To use the PyGEOS speed-ups within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install 
pygeos'

when I did import geopandas before executing all the commands above it worked absolutely fine.

result from pip list:
appdirs         1.4.4
atomicwrites    1.4.0
attrs           19.3.0
cfgv            3.1.0
click           7.1.2
click-plugins   1.1.1
cligj           0.5.0
colorama        0.4.3
cycler          0.10.0
descartes       1.1.0
distlib         0.3.0
e               1.4.5
filelock        3.0.12
Fiona           1.8.13
GDAL            3.0.4
geographiclib   1.50
geopandas       0.8.0+21.gd520ca3 d:\shortcut\hsl\venv\lib\site-packages
geopy           1.22.0
identify        1.4.20
kiwisolver      1.2.0
matplotlib      3.2.2
mock            4.0.2
more-itertools  8.4.0
munch           2.5.0
nodeenv         1.4.0
numpy           1.19.0
packaging       20.4
pandas          1.0.5
pip             20.1.1
pluggy          0.13.1
pre-commit      2.5.1
py              1.9.0
pygeos          0.7.1
pyparsing       2.4.7
pyproj          2.6.1.post1
pytest          5.4.3
python-dateutil 2.8.1
pytz            2020.1
PyYAML          5.3.1
setuptools      41.2.0
Shapely         1.8.dev0
six             1.15.0
toml            0.10.1
virtualenv      20.0.25
wcwidth         0.2.5

python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02)
