### ISSUE TITLE
Cannot save GeoDataFrames with more than one geometry in it. Fiona complains about  iterfeatures method. Good and easy to fix?

### ISSUE THREAD

**Issue by srenoes** [geopandas/geopandas#1490]
Since more than one geometry is now supported (thumbs up!) ... iterfeatures does not yet support it. Would be lucky to work on it as it is very easy to fix potentially if there is not other stuff that needs to be taken into consideration...

If I understood correctly , a geometric property must constain a shapely mapped geometry .value, not a shapely geometry object .....  then fiona should understand it, right?

Does geopandas already read multiple geoms?  I think so, at least if it reads dicts as properties,  but probably they are not (yet) converted back into shapely geometries ... yes? --> another thing to improve for multiple geom support.

(yet loading would not result in errors ... hopefully and you could fix it by hand )

**Comment by srenoes** [comment]
would be interesting and maybe worthwhile to explore cython based versions for speed with larger GeoDataFrames ... ?

**Comment by srenoes** [comment]
Like so (iterfeatures method)

                `if na == "drop":
                    properties_items = {
                        k: v for k, (v if not isinstance(v,BaseGeometry) else mapping(v)) in zip(properties_cols, row) if not pd.isnull(v)
                    }
                else:
                    properties_items = {k: (v if not isinstance(v,BaseGeometry) else mapping(v)) for k, v in zip(properties_cols, row)}`

the double if  in drop row looks nasty but within brackets its maybe still understandible :-D

**Comment by srenoes** [comment]
I hope this  doesnt need an example this time. Should be more or less obvious that fiona doesnt like key value pairs with shapely objects as values.

(In cases when there is a second geometry and not in geometry column it is not mapped by shapely)

**Comment by srenoes** [comment]
Ok that saving bit worked with the above modification of the code in iterfeatures worked and fiona ate it,.
Also the reading of geometries as features was as expected meaning it read columns full of dictionaries.

**Comment by srenoes** [comment]
I forked the repo and commited the changes to the master branch in my fork. Can you check if these changes make sense to integrate it into future versions? 

i will now also check if I can modify the reading code so that it also restores the geometries within features
that is probably a bit more stuff than these easy changes here

**Comment by srenoes** [comment]
"I forked the repo and commited the changes to the master branch in my fork. Can you check if these changes make sense to integrate it into future versions? "

It worked for some while but now there is some problems with inferring schema... 
I have written some test unit function writing and re-reading the gdf.
Now looking into the infer_schema function and convert type subfunction which does not work for me right now:
"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\geodataframe.py", line 724, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\io\file.py", line 240, in _to_file
    schema = infer_schema(df)
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\io\file.py", line 296, in infer_schema
    [
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\io\file.py", line 297, in <listcomp>
    (col, convert_type(col, _type))
  File "D:\shortcut\HSL\venv\lib\site-packages\geopandas\io\file.py", line 284, in convert_type
    out_type = type(np.zeros(1, in_type).item()).__name__
TypeError: Cannot interpret '<geopandas.array.GeometryDtype object at 0x000001D7CF7F0A00>' as a data type"

test function code 

`def test_to_file_multiple_geometries(self):
        p0 = Point(0, 0)
        p1 = Point(1, 1)
        p2 = Point(2, 2)
        p3 = Point(3, 3)
        gs1 = geopandas.GeoSeries([p0, p1])
        gs2 = geopandas.GeoSeries([p2, p3])
        # create a gdf with 2 geometries and different name
        # than geometry for the official geometry
        gdf = GeoDataFrame({"a": [1, 2], "b": gs1, "c": gs2}, geometry="c")
        tempfilename = os.path.join(self.tempdir, "two_geom.geojson")
        # write it to disc and reopen it again
        # there is some problem still with infering ... 
        # it does not recognise it, however when a driver is given
        # it seems to be fine ... hopefully now 
        gdf.to_file(tempfilename,driver='GeoJSON')  
        gdf2 = GeoDataFrame.from_file(tempfilename)
        
        assert isinstance(gdf2["a"], list)
        assert gdf2.columns[0:2].to_list() == ["a", "b"]
        # Don't know if the name of the geometry will be actually restored
        assert gdf2.columns[3] == "c"
        assert gdf2["a"].to_list() == [1, 2]
        assert isinstance(gdf2[gdf2._geometry_column_name], GeoSeries)
        assert isinstance(gdf2["b"][0], dict)
        # for future improvements on loading files with multiple geometries
        # assert isinstance(gdf["b"],GeoSeries)`

**Comment by martinfleis** [comment]
Thanks for the suggestions and your work. I think that this needs to be split into multiple parts (I am writing this also based on reply @brendan-ward gave you on gitter).

1) _adapt `iterfeatures` to handle multiple geometry columns_. The point of `iterfeatures` is to return JSON with `__geo_interface__`, which I guess does not support multiple geometries by itself. So the question is how to handle second geometry for the feature. Now we return `shapely.geometry`, which is not a string, so we need a string representation there (WKT, WKB, something else?).

2) _save to file_. Most of the file formats do not support multiple geometries. Not sure if any apart from feather/parquet. GeoPackage does support that? What happens if you open such a layer in QGIS? Does `fiona` support that?

3) _read from a file_. This again depends on fiona and file formats. We do support it for feather/parquet. What do we know about that?

**Comment by srenoes** [comment]
oh ok sorry didnt know that that you also work on it. err ... 

1. to return something else I used shapely mapping of that geometry whenever it is BaseGeometry. Like so. Ugly but relatively well readible with minimum changes to the prior code

````python
                if na == "drop":
                    properties_items = {
                        k: (v if not isinstance(v, BaseGeometry) else mapping(v))
                        for k, v in zip(properties_cols, row)
                        if not pd.isnull(v)
                    }
                else:
                    properties_items = {
                        k: (v if not isinstance(v, BaseGeometry) else mapping(v))
                        for k, v in zip(properties_cols, row)
                    }
``
with that I got some written file first but then some time later it failed in another bit of the code (inferring of the scheme for fiona).

2. changing the scheme
i checked first if you could use the same conversion than with the geometry column () , but that didnt work. Finally I got it to work with setting "str" as type. I had a geojson file with two geometries  and used the fio command line tool  to show info and the scheme showed "str" in place where there should be another geometry column. With that it wrote fine and also reopened fine.
though now it was a string which could be evaluated by eval(column[x]) to dict

```python
def convert_type(column, in_type):
        if in_type == object:
            return "str"
        if in_type.name.startswith("datetime64"):
            # numpy datetime type regardless of frequency
            return "datetime"
        if str(in_type) in types:
            out_type = types[str(in_type)]
        elif str(in_type) == "geometry":
            # I don't know what kind of
            # type geometry will refer to in future
            # anyway checking a geojson file
            # with two geometries using fio info (fiona CLI),
            # one as regular geometry, one as property
            # showed this geometry as "str" in "schema"
            out_type = "str"
        else:
            out_type = type(np.zeros(1, in_type).item()).__name__
        if out_type == "long":
            out_type = "int"
        if not _FIONA18 and out_type == "bool":
            raise ValueError(
                'column "{}" is boolean type, '.format(column)
                + "which is unsupported in file writing with fiona "
                "< 1.8. Consider casting the column to int type."
            )
        return out_type
```
Related to 1. Now what relates to how strict the __geom__interface is specified and if this mapping is ok I dont know. Hopefully it is because otherwise you cannot really use the iterfeature code for that purpose

Nothing done for 3.

**Comment by srenoes** [comment]
This is the code from the new function inserted into test_geodataframe.py
```python
def test_to_file_multiple_geometries(self):
        p0 = Point(0, 0)
        p1 = Point(1, 1)
        p2 = Point(2, 2)
        p3 = Point(3, 3)
        gs1 = geopandas.GeoSeries([p0, p1])
        gs2 = geopandas.GeoSeries([p2, p3])
        # create a gdf with 2 geometries and different name
        # than geometry for the official geometry
        gdf = GeoDataFrame({"a": [1, 2], "b": gs1, "c": gs2}, geometry="c")
        tempfilename = os.path.join(self.tempdir, "two_geom.shp")
        # write it to disc and reopen it again
        gdf.to_file(tempfilename)
        gdf2 = GeoDataFrame.from_file(tempfilename)
        # test feature column names
        assert gdf2.columns[0:2].to_list() == ["a", "b"]
        # geometry column name not restored:
        # assert gdf2.columns[3] == "c"
        # testing back conversion to GeoSeries of geometry column
        assert isinstance(gdf2[gdf2._geometry_column_name], GeoSeries)
        # testing content
        assert gdf2["a"].to_list() == [1, 2]
        assert isinstance(eval(gdf2["b"][0]), dict)
        # for future improvements on loading files with multiple geometries
        # assert isinstance(gdf["b"],GeoSeries)
```

**Comment by srenoes** [comment]
Related to 2. JOSM opens it but trashes the "property  geometry", but it does not fail and shows all the tags.
And same for QGIS. opens only the normal geometry (and no address points that are properties in my geojson, same as in josm)

Probably the right way is maybe to add different layers into geojson or well how it would be normally done ... never thought about that since I want to only save it to disc prior to further processing in geopandas

**Comment by srenoes** [comment]
another thing would be to add warnings in case people actually think they can open that in other programs than geopandas.. with two geometries, one as a geometry and one as a property.... 

fiona I guess is not really the problem... apart from what happened if you wanted to produce proper files with geometries put as they should. Now they are strings and that is supported by every format I guess

**Comment by srenoes** [comment]
['https://stackoverflow.com/questions/34044893/how-to-make-a-geometrycollection-in-geojson-with-a-single-point-polygon'](https://stackoverflow.com/questions/34044893/how-to-make-a-geometrycollection-in-geojson-with-a-single-point-polygon)
*As said in GeoJSON spec, a Feature object has exactly one geometry member, which is a Geometry object (or null).
A feature object must have a member with the name "geometry". The value of the geometry member is a geometry object as defined above or a JSON null value.
Among the possible geometry's you can indeed use a GeometryCollection, which must have a member geometries. The latter is an array of other geometries, i.e. your point, polygon, etc., or even another GeometryCollection.*

**Comment by brendan-ward** [comment]
@srenoes It isn't immediately obvious from the suggestions here what problem you're ultimately trying to solve.

I understand the goal is to serialize / deserialize multiple geometry columns.  There are a number of challenges going to / from data representations like GeoDataFrames and PostGIS tables that allow multiple geometry columns and traditional spatial formats like shapefiles and GeoJSON that do not.

The bigger question is _why_ you are trying to do this.  Is the larger goal here to avoid duplicating the non-geometry columns between multiple GeoDataFrames?  What are the different geometry representations that you are trying to keep tightly coupled here (e.g., polygon and associated centroid)?

The simplest solution seems like it would be to store each geometry column and closely associated attributes in its own file for serialization / deserialization.  You can join them together in GeoPandas for analysis, then split them back out for export for use in other GIS platforms (QGIS, etc).  Or keep them in a feather / parquet file for intermediate data with multiple geometry columns but not attempt to use these in other systems.

While you _can_ export extra geometry columns to WKT / WKB, that seems specific to your own analysis rather than something that should be added by GeoPandas to existing file formats.  That is instead something that should be taken up with future versions of those formats or new formats.  According to the [OGR RFC](https://trac.osgeo.org/gdal/wiki/rfc41_multiple_geometry_fields) on this topic, it looks like there are few formats that would actually support multiple geometry columns.  Geopackage [does not](https://github.com/opengeospatial/geopackage/issues/77)

**Comment by Rich1000** [comment]
For me it's all about being able to use GeoDataFrame.to_postgis() as a much simpler way to save and retrieve data from a Postgres database that has multiple geometry columns in each table. The alternative using psycopg2 is extremely fiddly and verbose.

**Comment by ljwolf** [comment]
I think this might be a case where "if you know you need it, you can learn how to do it."

RE Postgis, I think the request is very reasonable. But for most file formats, this is generally not supported. 

That said, @srenoes's solution makes sense (to serialize the secondary geometry columns into wkb/wkt and then write those out as text), but then other software won't really work well with that (e.g. QGIS could parse that, but the recommended paradigm *there* is multiple layers, too!) and we won't automatically aim to parse strings as if they were geometries after getting them from `fiona`.

**Comment by jorisvandenbossche** [comment]
Specifically for `to_postgis`/`read_postgis`, given that PostGIS supports multiple geometry columns, and given that for these functions we do not rely on fiona but have our own implementation, I think a contribution to add support for this in the PostGIS IO functions would indeed be welcome.
