### ISSUE TITLE
WinError 87 while running .exe file

### ISSUE THREAD

**Issue by timurkanaz** [geopandas/geopandas#1562]
Hello everyone! Maybe it is an offtop but I am a bit puzzled.. Just generated exe file for my GUI python program for working with some geospatial data and use folium,geopandas,shapely etc. However, while running some error occured:

`C:\Users\timna\dist\main>main.exe
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\io\file.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\timna\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\fiona\__init__.py", line 88, in <module>
  File "contextlib.py", line 113, in __enter__
  File "site-packages\fiona\_loading.py", line 54, in add_gdal_dll_directories
  File "os.py", line 1109, in add_dll_directory
OSError: [WinError 87] The parameter is incorrect
[11276] Failed to execute script main
`

It looks like libraries conflict...

What is the reason?Are there any possible ways to resolve this problem?

Thanks for response and help!

**Comment by jorisvandenbossche** [comment]
That seems a problem with Fiona (which is imported by GeoPandas). But I am personally not familiar with PyInstaller
