### ISSUE TITLE
BUG: sjoin on GeoDataFrames with MultiIndex as columns

### ISSUE THREAD

**Issue by adamjstewart** [geopandas/geopandas#1764]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

The following does not work as expected:
```python
import pandas as pd
import geopandas

df1 = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
gdf1 = geopandas.GeoDataFrame(df1, geometry=geopandas.points_from_xy(df1['location', 'x'], df1['location', 'y']))

df2 = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
gdf2 = geopandas.GeoDataFrame(df2, geometry=geopandas.points_from_xy(df2['location', 'x'], df2['location', 'y']))

gdf3 = geopandas.sjoin(gdf1, gdf2)
```
I get the following error message:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    gdf3 = geopandas.sjoin(gdf1, gdf2)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/tools/sjoin.py", line 62, in sjoin
    if any(left_df.columns.isin([index_left, index_right])) or any(
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 3846, in isin
    values = MultiIndex.from_tuples(values, names=self.names)._values
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 175, in new_meth
    return meth(self_or_cls, *args, **kwargs)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 537, in from_tuples
    return cls.from_arrays(arrays, sortorder=sortorder, names=names)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 466, in from_arrays
    return cls(
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 308, in __new__
    result._set_names(names)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 1431, in _set_names
    raise ValueError(
ValueError: Length of names must match number of levels in MultiIndex.
```
#### Problem description

This logic works fine in pure pandas:
```python
import pandas as pd

df1 = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
df2 = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])

df3 = pd.merge(df1, df2)
```

#### Expected Output

I would expect to be able to use `sjoin` on GeoDataFrames with MultiIndex as columns.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.7 (default, Dec 30 2020, 11:40:19)  [Clang 12.0.0 (clang-1200.0.32.28)]
executable : /Users/Adam/.spack/.spack-env/view/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/geos-3.8.1-vlrmv4vvnmfcvabpu6t4boks5fxtllko/lib/libgeos_c.dylib
GDAL       : 3.2.0
GDAL data dir: /Users/Adam/.spack/.spack-env/view/share/gdal
PROJ       : 7.1.0
PROJ data dir: /Users/Adam/.spack/.spack-env/view/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.0
fiona      : 1.8.18
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : None
pyproj     : 2.6.0
matplotlib : 3.3.3
mapclassify: 2.4.2
geopy      : 2.1.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None

</details>

**Comment by adamjstewart** [comment]
In reality, I want to use `sjoin` on one `GeoDataFrame` with a MultiIndex columns and another `GeoDataFrame` with an `Index` columns, but that doesn't even seem supported in `pandas`. I figured out how to convert the `Index` into a `MultiIndex`, but that doesn't help in `geopandas`.

**Comment by martinfleis** [comment]
I think that to make it work we would need to flatten the index before the join and reconstruct it after in here: https://github.com/geopandas/geopandas/blob/36521787c3e6484c00c2ffb8cdde60798d6d1616/geopandas/tools/sjoin.py#L145

You can try doing that manually, maybe using [`to_flat_index`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.MultiIndex.to_flat_index.html#pandas.MultiIndex.to_flat_index).

As you have probably noticed, having `MultiIndex` as columns is not really a common practice and there is a lot of cases where you hit the wall. That does not mean that it should not be supported though!

**Comment by adamjstewart** [comment]
I'm having some trouble getting that solution to work. I tried:
```python
gdf1.columns = gdf1.columns.to_flat_index()
gdf2.columns = gdf2.columns.to_flat_index()
gdf3 = geopandas.sjoin(gdf1, gdf2)
```
but I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/tools/sjoin.py", line 88, in sjoin
    sindex = right_df.sindex
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/generic.py", line 5460, in __getattr__
    return object.__getattribute__(self, name)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/base.py", line 593, in sindex
    self._generate_sindex()
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/base.py", line 100, in _generate_sindex
    _sindex = sindex_cls(self.geometry)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/generic.py", line 5460, in __getattr__
    return object.__getattribute__(self, name)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/geodataframe.py", line 171, in _get_geometry
    raise AttributeError(
AttributeError: No geometry data set yet (expected in column 'geometry'.)
```
because the `geometry` column has been renamed without telling geopandas about it. If I try to rename it:
```python
gdf1 = gdf1.set_geometry(('geometry',))  # or:
gdf1 = gdf1.set_geometry(('geometry', 'geometry'))
```
I get:
```
Traceback (most recent call last):
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('geometry',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/geodataframe.py", line 230, in set_geometry
    level = frame[col].values
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/geodataframe.py", line 828, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: ('geometry',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.8/site-packages/geopandas/geodataframe.py", line 232, in set_geometry
    raise ValueError("Unknown column %s" % col)
ValueError: Unknown column geometry
```
Is there a way to name the geometry column so that it has two levels? That might allow the merge to happen normally, since `pd.merge` supports it.

**Comment by adamjstewart** [comment]
Ah, nvm, had to use `('geometry', '')`.

**Comment by adamjstewart** [comment]
What's the inverse of `to_flat_index`? `from_tuples` doesn't seem to be working, unless I'm using it wrong...

**Comment by martinfleis** [comment]
@adamjstewart `gdf1.columns = pd.MultiIndex.from_tuples(gdf1.columns)` does not work for you?

**Comment by adamjstewart** [comment]
It does for `gdf1`, but not for `gdf3` because the column names end up like:
```
>>> gdf3
   ('location', 'x')_left  ('location', 'y')_left             (geometry, )  index_right  ('location', 'x')_right  ('location', 'y')_right
0                       1                       0  POINT (1.00000 0.00000)            0                        1                        0
1                       0                       1  POINT (0.00000 1.00000)            1                        0                        1
```
So it doesn't work if any of the column names overlap, or if `gdf1` is MultiIndex but `gdf2` is Index. I may not actually need to use a MultiIndex for gdf3 for my application though.
