### ISSUE TITLE
BUG: GeoDataFrame.groupby() sets geometry to naive (but still reports a crs)

### ISSUE THREAD

**Issue by dericke** [geopandas/geopandas#1777]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample

sample.geojson
```geojson
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"LineString","coordinates":[[102.0,0.0],[103.0,1.0],[104.0,0.0],[105.0,1.0]]},"properties":{"id":0,"prop0":"value0","prop1":0.0}},{"type":"Feature","geometry":{"type":"LineString","coordinates":[[106.0,0.0],[107.0,1.0],[108.0,0.0],[109.0,1.0]]},"properties":{"id":1,"prop0":"value0","prop1":0.0}},{"type":"Feature","geometry":{"type":"LineString","coordinates":[[110.0,0.0],[111.0,1.0],[112.0,0.0],[113.0,1.0]]},"properties":{"id":1,"prop0":"value0","prop1":0.0}}]}
```

```python3
import geopandas as gpd

gdf = gpd.read_file('sample.geojson')

initial_crs = gdf.crs

print(gdf.crs)
```
`epsg:4326`

```python3
gdf = gdf.groupby(["id"]).first()

print(gdf.crs)
print(initial_crs == gdf.crs)
```
```
epsg:4326 
True
```

```
gdf.to_crs(epsg=3857, inplace=True)
```
```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/geopandas/geodataframe.py", line 816, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/usr/local/lib/python3.9/site-packages/geopandas/geoseries.py", line 526, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
```

#### Problem description

When using `GeoDataFrame.groupby()`, the returned GDF cannot be reprojected, raising an exception which complains about a naive geometry. Oddly enough, the returned GDF's `.crs` property still reports the same CRS as the input GDF.

#### Expected Output

A GDF with the same CRS as the input, which can immediately be reprojected with `.to_crs()`.

#### Output of ``geopandas.show_versions()``

<details>

```
SYSTEM INFO
-----------
python     : 3.9.1 (default, Dec 29 2020, 07:31:08)  [Clang 11.0.0 (clang-1100.0.33.17)]
executable : /usr/local/opt/python@3.9/bin/python3.9
machine    : macOS-10.14.6-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.0
GEOS lib   : /usr/local/Cellar/geos/3.9.0/lib/libgeos_c.dylib
GDAL       : 3.2.0
GDAL data dir: None
PROJ       : 7.2.0
PROJ data dir: /usr/local/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.5
fiona      : 1.8.18
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.0.post1
matplotlib : 2.2.5
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
```

</details>

**Comment by martinfleis** [comment]
Thanks for the report. I can confirm that the resulting GeoSeries and GeometryArray lost CRS during the operation, while the crs attribute of GeoDataFrame is present. We should have a look into that, to pass CRS correctly to newly created GeometryArray.

**Comment by 0phoff** [comment]
Not sure whether my issue is related to that, but I rather comment here before opening a new issue.
When inside a `df.groupby.apply()`, in the function the `_geometry_column_name` is set to the default "geometry" name and not the column of the base dataframe that gets applied.
This means that you cannot use the `df.geometry` in the apply function.

**Comment by martinfleis** [comment]
@0phoff thanks for the notice! It is probably related. It sounds that our custom attributes are generally broken in `groupby`.

**Comment by AndrewAnnex** [comment]
I am running into this issue oddly for code that has been working for a while, but I think I recently updated to pandas 1.3 so maybe that is part of the issue?

**Comment by kirkhansen** [comment]
> Not sure whether my issue is related to that, but I rather comment here before opening a new issue. When inside a `df.groupby.apply()`, in the function the `_geometry_column_name` is set to the default "geometry" name and not the column of the base dataframe that gets applied. This means that you cannot use the `df.geometry` in the apply function.

Potentially related to this, code that worked with pandas 1.2.4 does not work with pandas 1.3.x. Dumb example below...

```python
import geopandas

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
print(world.crs) 
print(world.groupby("continent").apply(lambda x: x).crs)
```

pandas 1.2.4 output
```
epsg:4326
epsg:4326
```

pandas 1.3.4 output
```
epsg:4326
None
```

I can make a separate issue if it turns out not to be related.

**Comment by m-richards** [comment]
Closing this as groupby() does set the crs to None but the result the resultant dataframe also has the CRS set to None i.e. `print(initial_crs == gdf.crs)` in the original example now returns false.

With the flexibility of groupby it's not possible to trace which crs should be passed down (unless we were to special case the behaviour of things like first(). If we did want to purse that, we can track that as a feature in a new issue.
