### ISSUE TITLE
BUG: Bug in assert_geoseries_equal in 0.9.0

### ISSUE THREAD

**Issue by johnflavin** [geopandas/geopandas#1863]
When running `assert_geoseries_equal` with `check_less_precise=False`, if all geometries which are not equal _are_ almost equal an error is thrown when generating the error string.

```python
>>> import geopandas
>>> import geopandas.testing
>>> geopandas.testing.assert_geoseries_equal(geopandas.GeoSeries.from_wkt(["POINT (0 0)"]), geopandas.GeoSeries.from_wkt(["POINT (0.0000001 0)"]), check_less_precise=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john.flavin/repos/geopandas/geopandas/testing.py", line 138, in assert_geoseries_equal
    _check_equality(left, right, check_less_precise)
  File "/Users/john.flavin/repos/geopandas/geopandas/testing.py", line 184, in _check_equality
    _truncated_string(unequal_left_geoms.iloc[0]),
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
There should be an `AssertionError` raised. Instead we get an error from pandas when trying to generate the assertion error message. 

The error stems from these lines https://github.com/geopandas/geopandas/blob/master/geopandas/testing.py#L175-L177:
```python
        if not geom_equals(left, right):
            unequal_left_geoms = left[~left.geom_almost_equals(right)]
            unequal_right_geoms = right[~left.geom_almost_equals(right)]
```
These lines are comparing the geometries with `geom_equals` (which is correct, since we specified `check_less_precise=False`). But if that finds any unequal geometries, then it tries to locate them using `~geom_almost_equals`. This is incorrect. In my example, all the geometries are not equal but _are_ almost equal, so this line finds nothing. This triggers the `IndexError` later when we try to pull an element out of this empty series.

**Comment by martinfleis** [comment]
Good catch! Thanks!

**Comment by johnflavin** [comment]
No worries! The new assertion error messages are very nice. Thanks for making them.
