### ISSUE TITLE
BUG: GeoSeries.from_wkt fails on nullable Series input

### ISSUE THREAD

**Issue by qwertystop** [geopandas/geopandas#1879]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import geopandas as gpd
>>> import pandas as pd
>>> geopandas.options.use_pygeos = False
>>> ser = pd.Series(["POINT (10 1)", pd.NA], dtype="string")
>>> ser
0    POINT (10 1)
1            <NA>
dtype: string
>>> gpd.GeoSeries.from_wkt(ser)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/geoseries.py", line 446, in from_wkt
    return cls._from_wkb_or_wkb(from_wkt, data, index=index, crs=crs, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/geoseries.py", line 459, in _from_wkb_or_wkb
    return cls(from_wkb_or_wkt_function(data, crs=crs), index=index, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/array.py", line 220, in from_wkt
    return GeometryArray(vectorized.from_wkt(data), crs=crs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/_vectorized.py", line 203, in from_wkt
    if geom is not None and len(geom):
TypeError: object of type 'NAType' has no len()
>>> gpd.GeoSeries.from_wkt(ser.dropna())
0    POINT (10.00000 1.00000)
dtype: geometry
```

Or, if PyGEOS is enabled, it's even worse:

```
>>> geopandas.options.use_pygeos = True
>>> gpd.GeoSeries.from_wkt(ser)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/geoseries.py", line 446, in from_wkt
    return cls._from_wkb_or_wkb(from_wkt, data, index=index, crs=crs, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/geoseries.py", line 459, in _from_wkb_or_wkb
    return cls(from_wkb_or_wkt_function(data, crs=crs), index=index, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/array.py", line 220, in from_wkt
    return GeometryArray(vectorized.from_wkt(data), crs=crs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/_vectorized.py", line 196, in from_wkt
    return pygeos.from_wkt(data)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pyg
eos/io.py", line 181, in from_wkt
    return lib.from_wkt(geometry, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pan
das/core/arrays/numpy_.py", line 237, in __array_ufunc__
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: Expected bytes, got NAType
>>> gpd.GeoSeries.from_wkt(ser.dropna())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/geoseries.py", line 446, in from_wkt
    return cls._from_wkb_or_wkb(from_wkt, data, index=index, crs=crs, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/geoseries.py", line 459, in _from_wkb_or_wkb
    return cls(from_wkb_or_wkt_function(data, crs=crs), index=index, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/array.py", line 220, in from_wkt
    return GeometryArray(vectorized.from_wkt(data), crs=crs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geo
pandas/_vectorized.py", line 196, in from_wkt
    return pygeos.from_wkt(data)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pyg
eos/io.py", line 181, in from_wkt
    return lib.from_wkt(geometry, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pan
das/core/arrays/numpy_.py", line 254, in __array_ufunc__
    result = type(self)(result)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pan
das/core/arrays/string_.py", line 195, in __init__
    self._validate()
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pan
das/core/arrays/string_.py", line 200, in _validate
    raise ValueError("StringArray requires a sequence of strings or pandas.NA")
ValueError: StringArray requires a sequence of strings or pandas.NA
```

#### Problem description

Currently, if GeoSeries.from_wkt is given a pandas Series with missing values represented as NaN or pd.NA, it raises as shown above. These are very common represenations of missing values in most Pandas code – the standard representations, the former in the case of a Series of dtype `object` and the latter in the case of a Series of dtype `StringDType`. This can be worked around by dropping null values from a Series before putting it in, but then the output is a GeoSeries of a different shape from the input which will require realignment.

And if PyGEOS is enabled, dropping nulls isn't enough – you also have to upcast from `StringDType` to `object` *in addition* to dropping nulls.

#### Output of ``gpd.GeoSeries.from_wkt(ser)``

<details>

Either:
```
0    POINT (10.00000 1.00000)
1    None
```
or
```
0    POINT (10.00000 1.00000)
1    <NA>
```

</details>

**Comment by jorisvandenbossche** [comment]
@qwertystop Thanks for the report! And yes, we should ideally support the nullable string dtype as input for `from_wkt`

**Comment by qwertystop** [comment]
(it's also a bit odd generally that you standardized on `None` for missing data when Pandas tends towards `pandas.NA` or `NaN` as appropriate, but that's beyond the scope of this and possibly too late to change)

**Comment by johnflavin** [comment]
I can reproduce the things you’re seeing, but I think there are three different underlying issues here. 

### 0. Setup
Just like you had it:
```python
>>> import geopandas as gpd
>>> import pandas as pd
>>> ser = pd.Series(["POINT (10 1)", pd.NA], dtype="string")
```

### 1. `from_wkt` with `pd.NA`, no `pygeos`
```python
>>> gpd.options.use_pygeos = False
>>> gpd.GeoSeries.from_wkt(ser)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnflavin/repos/geopandas/geopandas/geoseries.py", line 446, in from_wkt
    return cls._from_wkb_or_wkb(from_wkt, data, index=index, crs=crs, **kwargs)
  File "/Users/johnflavin/repos/geopandas/geopandas/geoseries.py", line 459, in _from_wkb_or_wkb
    return cls(from_wkb_or_wkt_function(data, crs=crs), index=index, **kwargs)
  File "/Users/johnflavin/repos/geopandas/geopandas/array.py", line 220, in from_wkt
    return GeometryArray(vectorized.from_wkt(data), crs=crs)
  File "/Users/johnflavin/repos/geopandas/geopandas/_vectorized.py", line 203, in from_wkt
    if geom is not None and len(geom):
TypeError: object of type 'NAType' has no len()
```
This one is straightforward to fix in `geopandas`. I have fixed it on a branch. With that branch active, I get this result instead:
```python
>>> gpd.options.use_pygeos = False
>>> gpd.GeoSeries.from_wkt(ser)
0    POINT (10.00000 1.00000)
1                        None
dtype: geometry
```

### 2. `from_wkt` with `pd.NA`, with `pygeos`
```python
>>> gpd.options.use_pygeos = True
>>> gpd.GeoSeries.from_wkt(ser)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnflavin/repos/geopandas/geopandas/geoseries.py", line 446, in from_wkt
    return cls._from_wkb_or_wkb(from_wkt, data, index=index, crs=crs, **kwargs)
  File "/Users/johnflavin/repos/geopandas/geopandas/geoseries.py", line 459, in _from_wkb_or_wkb
    return cls(from_wkb_or_wkt_function(data, crs=crs), index=index, **kwargs)
  File "/Users/johnflavin/repos/geopandas/geopandas/array.py", line 204, in from_wkt
    return GeometryArray(vectorized.from_wkt(data), crs=crs)
  File "/Users/johnflavin/repos/geopandas/geopandas/_vectorized.py", line 182, in from_wkt
    return pygeos.from_wkt(data)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pygeos/io.py", line 181, in from_wkt
    return lib.from_wkt(geometry, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/numpy_.py", line 237, in __array_ufunc__
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: Expected bytes, got NAType
```
This one has nothing to do with `geopandas`; we can reproduce this same error directly in `pygeos` bypassing `geopandas` entirely.
```python
>>> import pygeos
>>> pygeos.from_wkt(ser.values)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pygeos/io.py", line 181, in from_wkt
    return lib.from_wkt(geometry, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/numpy_.py", line 237, in __array_ufunc__
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: Expected bytes, got NAType
```

I don't understand the `numpy` `ufunc` mechanism that `pygeos` uses, so I don't understand if the problem here is in `pygeos` or `numpy` or something else. But someone could open an issue in `pygeos` about that.

### 3. `from_wkt` with `StringArray`, with `pygeos`
When you simply use a series with a string dtype even without any NA values you get an error as well.
```python
>>> gpd.options.use_pygeos = True
>>> gpd.GeoSeries.from_wkt(ser.dropna())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnflavin/repos/geopandas/geopandas/geoseries.py", line 446, in from_wkt
    return cls._from_wkb_or_wkb(from_wkt, data, index=index, crs=crs, **kwargs)
  File "/Users/johnflavin/repos/geopandas/geopandas/geoseries.py", line 459, in _from_wkb_or_wkb
    return cls(from_wkb_or_wkt_function(data, crs=crs), index=index, **kwargs)
  File "/Users/johnflavin/repos/geopandas/geopandas/array.py", line 204, in from_wkt
    return GeometryArray(vectorized.from_wkt(data), crs=crs)
  File "/Users/johnflavin/repos/geopandas/geopandas/_vectorized.py", line 182, in from_wkt
    return pygeos.from_wkt(data)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pygeos/io.py", line 181, in from_wkt
    return lib.from_wkt(geometry, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/numpy_.py", line 254, in __array_ufunc__
    result = type(self)(result)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/string_.py", line 195, in __init__
    self._validate()
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/string_.py", line 200, in _validate
    raise ValueError("StringArray requires a sequence of strings or pandas.NA")
ValueError: StringArray requires a sequence of strings or pandas.NA
```
This one is also not caused by any problem in `geopandas`; I can reproduce it with just `pygeos`.
```python
>>> pygeos.from_wkt(ser.dropna().values)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pygeos/io.py", line 181, in from_wkt
    return lib.from_wkt(geometry, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/numpy_.py", line 254, in __array_ufunc__
    result = type(self)(result)
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/string_.py", line 195, in __init__
    self._validate()
  File "/usr/local/Caskroom/miniconda/base/envs/geopandas-dev/lib/python3.9/site-packages/pandas/core/arrays/string_.py", line 200, in _validate
    raise ValueError("StringArray requires a sequence of strings or pandas.NA")
ValueError: StringArray requires a sequence of strings or pandas.NA
```
This one seems to be triggered by passing a `StringArray` into `from_wkt`. If I make the same wkt series but don't give it the string dtype things work fine.
```python
>>> ser2 = pd.Series(["POINT (10 1)", pd.NA])
>>> pygeos.from_wkt(ser2.dropna().values)
array([<pygeos.Geometry POINT (10 1)>], dtype=object)
```
The weird thing is that I can't reproduce the error without `pygeos`. If we go down to the bottom of the traceback we see the error is thrown from `StringArray._validate` [here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/string_.py#L219-L220):
```python
        if len(self._ndarray) and not lib.is_string_array(self._ndarray, skipna=True):
            raise ValueError("StringArray requires a sequence of strings or pandas.NA")
```
But if we call `_validate` on our string array directly, we don't see the error.
```python
>>> ser.dropna().values._validate()
```
Something wrong is happening in `pygeos.from_wkt` with `StringArray` inputs, but I can't tell exactly what. This could also be opened as a `pygeos` issue. But I think it is separate from the NA issue in 2.

**Comment by m-richards** [comment]
Closing this, #1891 fixes the geopandas, pygeos is no longer around and https://github.com/pandas-dev/pandas/pull/62498 progressed the pandas side. Pandas issue is still not fully closed (https://github.com/pandas-dev/pandas/issues/40800) but the geopandas case is
