### ISSUE TITLE
BUG: to_file cannot write dataframes containing categorical data (or numerically-named columns?)

### ISSUE THREAD

**Issue by qwertystop** [geopandas/geopandas#1883]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> import geopandas as gpd
>>> df = pd.DataFrame([["a", "POINT ( 0 0 )"], ["b", "POINT ( 0 1 )"], ["a", "POINT ( 1 0 )"], ["b", "POINT ( 1 1 )"]], columns=["0", "geometry"])
>>> df["0"] = df["0"].astype("category")
>>> gdf = gpd.GeoDataFrame(df, geometry=gpd.GeoSeries.from_wkt(df["geometry"]))
>>> gdf
   0                 geometry
0  a  POINT (0.00000 0.00000)
1  b  POINT (0.00000 1.00000)
2  a  POINT (1.00000 0.00000)
3  b  POINT (1.00000 1.00000)
>>> gdf.dtypes
0           category
geometry    geometry
dtype: object
>>> gdf.to_file("foo.geojson", driver="GeoJSON")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1086, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geopandas/io/file.py", line 304, in _to_file
    schema = infer_schema(df)
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geopandas/io/file.py", line 354, in infer_schema
    [
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geopandas/io/file.py", line 355, in <listcomp>
    (col, convert_type(col, _type))
  File "/home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/geopandas/io/file.py", line 348, in convert_type
    out_type = type(np.zeros(1, in_type).item()).__name__
TypeError: Cannot interpret 'CategoricalDtype(categories=['a', 'b'], ordered=False)' as a data type
```

And, after upcasting to string:

```python
>>> gdf["0"] = gdf["0"].astype("string")
>>> gdf.to_file("foo.geojson", driver="GeoJSON")
>>> 
```

#### Problem description

If a dataframe contains categorical data in non-geo columns, it cannot be written to a file without converting to another data type first, which on large datasets with many repeated strings (e.g. land parcels with zoning or use codes or city/region names) is potentially infeasible due to memory consumption. I have not tested categorical geo data. I have tested output filetypes of GeoJSON and GML and gotten identical stack traces, so assume the issue is not filetype-dependent.

#### Expected Output
A file containing:
```
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "0": "a" }, "geometry": { "type": "Point", "coordinates": [ 0.0, 0.0 ] } },
{ "type": "Feature", "properties": { "0": "b" }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } },
{ "type": "Feature", "properties": { "0": "a" }, "geometry": { "type": "Point", "coordinates": [ 1.0, 0.0 ] } },
{ "type": "Feature", "properties": { "0": "b" }, "geometry": { "type": "Point", "coordinates": [ 1.0, 1.0 ] } }
]
}
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.1 (default, Feb 15 2021, 10:49:59)  [GCC 10.2.0]
executable : /home/qwertystop/.pyenv/versions/neighborhoody-data-etl/bin/python
machine    : Linux-5.11.6-arch1-1-x86_64-with-glibc2.33

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /usr/lib/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: /home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 7.2.1
PROJ data dir: /home/qwertystop/.pyenv/versions/neighborhoody-data-etl/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.2
fiona      : 1.8.18
numpy      : 1.20.1
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.1
matplotlib : 3.3.4
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
I can confirm the behaviour, but I am less sure what to do about it. The reason why this happens is simple - geospatial data formats do not support categorical dtype. Therefore you have to convert it to something else, there's no other way around.

So you either have to convert dtype yourself, as you did here or we could do it automatically. However, categorial dtype can contain strings as well as integers. I am tempted to leave this conversion to a user rather than doing a bit unpredictable operation under the hood.

You are right that there may be memory implications though. The only solution around that would be to implement the conversion within the loop here (replace `df.iterfeatures()` by a custom loop) but I am not a fan of that either as it could become relatively complicated piece of code.

https://github.com/geopandas/geopandas/blob/910131ec3af6143ccac33de4b66e9f8267c6fc7c/geopandas/io/file.py#L327-L330

I would personally just expand that error message to say what needs to be done by a user. But I am happy to hear other suggestions.

**Comment by jorisvandenbossche** [comment]
I think that, generally speaking, in pandas it converts the categorical column to the dtype of its categories (so to string for string cateegories, int for int categories, etc) for formats which don't support categorical natively. 

At least, for all formats with a text representation (eg csv or html in case of pandas, or GeoJSON in case of geopandas), the representation would exactly be the same in both cases. 
So certainly for those cases, I think it would be nice to automatically support categorical columns.

**Comment by jorisvandenbossche** [comment]
Actually, looking at the `iterfeatures` implementation, we already have a `astype(object)` conversion at the moment (this could probably be optimized, though), so that should already work with categorical columns:

https://github.com/geopandas/geopandas/blob/f5c54edfaac04b42ea45557466e3819cbbb2499f/geopandas/geodataframe.py#L816-L817

So I think it is mostly a matter of updating `io/file.py::convert_type` to handle categorical dtype. 

Of course, you still have the possibly surprising memory spike. Although I think the current implementation of `iterfeatures` has that for normal columns as well .. And I also think that should be solvable to only convert the category inside the loop, and not all up-front.

**Comment by damanad** [comment]
I recently encountered this error and, as Martin says, in general, the user may want to deal with it externally because of this: If you want to preserve the memory/storage savings enabled by categorical pandas columns, then you should save the integer codes (the indexes in pandas nomenclature) as feature properties and keep a separate 'legend' containing the category mapping. Some GIS file formats will allow you to save it altogether (even in geojson, albeit breaking the standard). 
However, as Joris observes, almost everything from geopandas to_file() is ready for automatic support of categorical columns. We just need to prevent convert_type from crashing. The simplest way is to force the dtype to str when a pandas categorical is found (already done for a generic object). This will work as long as the dtype of the categories can be converted to str (if not str already), which is pretty much most of the cases. The only change needed is this :
https://github.com/geopandas/geopandas/blob/f5c54edfaac04b42ea45557466e3819cbbb2499f/geopandas/io/file.py#L339-L344
to:
```python
def convert_type(column, in_type):
        if (in_type == object) | (isinstance(in_type, pd.CategoricalDtype):
            return "str"
        if in_type.name.startswith("datetime64"):
            # numpy datetime type regardless of frequency
            return "datetime"
```

**Comment by qwertystop** [comment]
Yes, but that's true for all categoricals, including in baseline Pandas – but in just about every other context, categoricals are automatically converted to the value they represent as necessary. "Automatically translate from categorical to underlying objects for operations on those objects" is the default behavior for everything, including writing, except this. In Pandas, if you want to read and write while maintaining categorical dtypes using a separate legend table, you have to do that yourself; persistent storage is cheaper than RAM, and it's much simpler (in default pandas with e.g. `read_csv`) to store the data expanded and recompress to categorical on read (just use `dtype='category'`, and possibly also use `chunksize` and concat the chunks) than it is to use a second table. Geopandas, as an extension to the Pandas API, should follow that pattern, yes?
