### ISSUE TITLE
BUG: OSError: Could not find lib c or load any of its variants []

### ISSUE THREAD

**Issue by henrykironde** [geopandas/geopandas#1893]
- [x] I have checked that this issue has not already been reported.

Could be related to  (#1567) (#395)
- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import geopandas
```

#### Problem description

The import fails and causes any other import in python to fail
Upon uninstalling, Python goes to to working mode

```Python
Traceback (most recent call last):
  File "/Users/henrykironde/miniconda3/envs/deepforest/bin/retriever", line 5, in <module>
    from retriever.__main__ import main
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/retriever/__init__.py", line 7, in <module>
    from retriever.lib.engine_tools import set_proxy, create_home_dir
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/retriever/lib/__init__.py", line 3, in <module>
    from .create_scripts import create_package
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/retriever/lib/create_scripts.py", line 16, in <module>
    from retriever.lib.engine import Engine
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/retriever/lib/engine.py", line 29, in <module>
    from retriever.lib.engine_tools import geojson2csv
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/retriever/lib/engine_tools.py", line 20, in <module>
    import geopandas
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/geopandas/_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/geopandas/_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/geopandas/_compat.py", line 10, in <module>
    import shapely.geos
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/shapely/geos.py", line 138, in <module>
    free = load_dll('c').free
  File "/Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages/shapely/geos.py", line 62, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants []
```

#### Output of ``geopandas.show_versions()``

<details>

```python
(deepforest) ➜  retriever git:(gdb) ✗ pip install geopandas
Collecting geopandas
  Downloading geopandas-0.9.0-py2.py3-none-any.whl (994 kB)
     |████████████████████████████████| 994 kB 7.8 MB/s 
Requirement already satisfied: shapely>=1.6 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from geopandas) (1.7.0)
Requirement already satisfied: fiona>=1.8 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from geopandas) (1.8.13.post1)
Requirement already satisfied: pandas>=0.24.0 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from geopandas) (1.1.3)
Collecting pyproj>=2.2.0
  Downloading pyproj-3.0.1-cp36-cp36m-macosx_10_9_x86_64.whl (7.4 MB)
     |████████████████████████████████| 7.4 MB 38.8 MB/s 
Requirement already satisfied: cligj>=0.5 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from fiona>=1.8->geopandas) (0.5.0)
Requirement already satisfied: attrs>=17 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from fiona>=1.8->geopandas) (20.2.0)
Requirement already satisfied: six>=1.7 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: click<8,>=4.0 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from fiona>=1.8->geopandas) (7.0)
Requirement already satisfied: munch in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: click-plugins>=1.0 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: pytz>=2017.2 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from pandas>=0.24.0->geopandas) (2017.3)
Requirement already satisfied: numpy>=1.15.4 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from pandas>=0.24.0->geopandas) (1.19.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: certifi in /Users/henrykironde/miniconda3/envs/DeepForest/lib/python3.6/site-packages (from pyproj>=2.2.0->geopandas) (2020.6.20)
Installing collected packages: pyproj, geopandas
Successfully installed geopandas-0.9.0 pyproj-3.0.1
```
[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by henrykironde** [comment]
OS: Mac OS Big Sur 11.2.1
Python 3.6 /miniconda

**Comment by martinfleis** [comment]
This is an installation issue. Since you are using `conda` to manage environments, can you also use it to install geopandas? That is the recommended installation anyway.

```
conda install -c conda-forge geopandas
```

`pip install` apparently didn't install `shapely/geos` correctly in your case.

**Comment by henrykironde** [comment]
Yes that worked so fine.  Wonder why that is so.
Anyway I will go on and close this issue.
