### ISSUE TITLE
BUG: to_crs indicates current crs is 'naive' but it is set

### ISSUE THREAD

**Issue by jtamerius** [geopandas/geopandas#1950]
- [ X] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of geopandas.

---

#### Problem description
I have a geopandas dataframe that has a crs...

```
```python
gdf_out.crs

<Projected CRS: EPSG:3310>
Name: NAD83 / California Albers
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: United States (USA) - California.
- bounds: (-124.45, 32.53, -114.12, 42.01)
Coordinate Operation:
- name: California Albers
- method: Albers Equal Area
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

```

However, when I try to reproject I get the following error:

```
gdf_out.to_crs(epsg=4326)

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\site-packages\geopandas\geodataframe.py", line 1247, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\site-packages\geopandas\geoseries.py", line 1028, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\caret_evi\lib\site-packages\geopandas\array.py", line 780, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
```

#### Expected Output
I would expect that I should not get an error since there is a set crs.

#### Output of ``geopandas.show_versions()``

<details>

```
SYSTEM INFO
-----------
python     : 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 04:59:43) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\me\AppData\Local\Continuum\anaconda3\envs\caret_evi\python.exe
machine    : Windows-10-10.0.18362-SP0
GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.2.2
GDAL data dir: None
PROJ       : 8.0.0
PROJ data dir: C:\Users\me\AppData\Local\Continuum\anaconda3\envs\caret_evi\Library\share\proj
PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.4
fiona      : 1.8.19
numpy      : 1.20.2
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.1
matplotlib : 3.4.2
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None
```

</details>

**Comment by martinfleis** [comment]
Hi, thanks for the report. Can you try to provide a reproducible example? I am not able to see the same behaviour. You can follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to create the example.

**Comment by jorisvandenbossche** [comment]
Given the lack of a reproducible example, I am going to close this issue.  
@jtamerius if you still have this issue and could provide more information, we can certainly reopen the issue.
