### ISSUE TITLE
BUG: GeoSeries.explode() class function conflicts with pandas Series.explode() class function

### ISSUE THREAD

**Issue by Robbie-Palmer** [geopandas/geopandas#2061]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
from geopandas import GeoDataFrame, GeoSeries
from shapely.geometry import MultiPoint

nested_df = GeoDataFrame(dict(
    places=[MultiPoint([(0, 0), (1, 1)]), MultiPoint([(10, 10), (11, 11)])],
    labels=[['Location', 'Cafe'], ['Cafe', 'Location']]
))
exploded = nested_df.apply(GeoSeries.explode)
```

#### Problem description

An error is raised when the `GeoSeries.explode` class function is applied to non-geometric pandas `Series` that are wrapped in a `GeoSeries` wrapper within the `GeoDataFrame`.

<details>

Traceback (most recent call last):
  File "./gpd_explode_min_reprex.py", line 8, in <module>
    exploded = nested_df.apply(GeoSeries.explode)
  File "./lib/python3.8/site-packages/geopandas/geodataframe.py", line 1361, in apply
    result = super().apply(
  File "./lib/python3.8/site-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "./lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "./lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "./lib/python3.8/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "./lib/python3.8/site-packages/geopandas/geoseries.py", line 843, in explode
    for idx, s in self.geometry.iteritems():
  File "./lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'geometry'

</details>

It would be great if in this case it would fall back to the `Series.explode` class function.

This would be in line with expected behaviour following #1719 resolved by #1720 and related to #1140
The referenced work has implemented the fallback for the instance methods `explode` but not the class method.

Below is an example of functioning code with the intended result, using the instance method instead of the `GeoSeries.explode` class method:

```python
from geopandas import GeoDataFrame
from shapely.geometry import MultiPoint

nested_df = GeoDataFrame(dict(
    places=[MultiPoint([(0, 0), (1, 1)]), MultiPoint([(10, 10), (11, 11)])],
    labels=[['Location', 'Cafe'], ['Cafe', 'Location']]
))
unpacked_series = dict()
for col in nested_df:
    unpacked_series[col] = nested_df[col].explode()
exploded = GeoDataFrame(unpacked_series)
```

#### Expected Output

```
          places    labels
0    POINT (0 0)  Location
0    POINT (1 1)      Cafe
1  POINT (10 10)      Cafe
1  POINT (11 11)  Location
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0]
machine    : Linux-5.4.0-80-generic-x86_64-with-glibc2.17
GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.7.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /home/robbie/miniconda3/envs/crcphenotype/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 8.0.1
PROJ data dir: /home/robbie/miniconda3/envs/crcphenotype/lib/python3.8/site-packages/pyproj/proj_dir/share/proj
PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.5
fiona      : 1.8.20
numpy      : 1.19.1
shapely    : 1.8a1
rtree      : None
pyproj     : 3.1.0
matplotlib : 3.3.4
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 3.0.0
pygeos     : None

</details>

**Comment by m-richards** [comment]
I'm going to close this as I don't see a motivating situation for fixing this. We don't support non geometry data in a GeoSeries, and if a user is calling the `explode` as a classmethod, and not from an instance I think it's fair game they do their own error handling. Happy to reconsider if a motivating use case is put forward.
