### ISSUE TITLE
Kernel Dies when trying to plot Geopandas DataFrame

### ISSUE THREAD

**Issue by m2rik** [geopandas/geopandas#2204]
- [ ] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable
data.plot()
Error: Kernel is dead
at g._sendKernelShellControl (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:1006305)
at g.sendShellMessage (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:1006074)
at g.requestExecute (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:1008616)
at d.requestExecute (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:37:328037)
at S.requestExecute (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:32:19306)
at w.executeCodeCell (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:300924)
at w.execute (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:300551)
at w.start (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:296215)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async t.CellExecutionQueue.executeQueuedCells (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:310950)
at async t.CellExecutionQueue.start (c:\Users\750033101\.vscode\extensions\ms-toolsai.jupyter-2021.9.1101343141\out\client\extension.js:52:310490)
```

**Comment by martinfleis** [comment]
Hi @m2rik. Thanks for the report but please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question. We need more information from you. In my VS Code, plotting works as expected and without further information, there's not much we can do.
