### ISSUE TITLE
BUG: 'NoneType' object has no attribute '_geom'

### ISSUE THREAD

**Issue by iamtekson** [geopandas/geopandas#2264]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
I have tried to upload my point dataset to PostGIS using following function,

```python
gdf = geopandas.read_file(shpInput)
engine = create_engine(connstr)
gdf.to_postgis(name='table', con=engine, if_exists='replace')
```

#### Problem description
The error occurs when there is a problem in the geodataframe. The geodataframe can read the `None` geometry as well, but when we are trying to upload to PostGIS, we need to validate the data frame.

#### Output of ``geopandas.show_versions()``
0.10.2

**Comment by iamtekson** [comment]
I have tried the following things before uploading to the PostGIS and it worked,

```python
gdf = gdf[gdf.is_valid]
```

Not sure whether this needs to implement on the geopandas to_postgis method or not.

**Comment by martinfleis** [comment]
Hi, thanks for the report. I think that we should not silently filter out invalid geometries but we should certainly wrap this error in a more informative one.

**Comment by martinfleis** [comment]
@iamtekson I know it has been a while but do you, by any chance have the full traceback? I am trying to figure out if it comes from this line (I suppose so) https://github.com/geopandas/geopandas/blob/8bc873c3cac3439d2a616cb3b883592edfe0b373/geopandas/io/sql.py#L88

**Comment by jorisvandenbossche** [comment]
Also this line might error if there are missing values:

https://github.com/geopandas/geopandas/blob/8bc873c3cac3439d2a616cb3b883592edfe0b373/geopandas/io/sql.py#L286

**Comment by karolzlot** [comment]
@iamtekson

```
Traceback (most recent call last):
   ...
   ...
   ...
  File "/home/user1/anaconda3/envs/env1/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1808, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/home/user1/anaconda3/envs/env1/lib/python3.10/site-packages/geopandas/io/sql.py", line 402, in _write_postgis
    gdf = _convert_to_ewkb(gdf, geom_name, srid)
  File "/home/user1/anaconda3/envs/env1/lib/python3.10/site-packages/geopandas/io/sql.py", line 286, in _convert_to_ewkb
    geoms = [dumps(geom, srid=srid, hex=True) for geom in gdf[geom_name]]
  File "/home/user1/anaconda3/envs/env1/lib/python3.10/site-packages/geopandas/io/sql.py", line 286, in <listcomp>
    geoms = [dumps(geom, srid=srid, hex=True) for geom in gdf[geom_name]]
  File "/home/user1/anaconda3/envs/env1/lib/python3.10/site-packages/shapely/wkb.py", line 57, in dumps
    geom = lgeos.GEOSGeom_clone(ob._geom)
AttributeError: 'NoneType' object has no attribute '_geom'
```
