### ISSUE TITLE
BUG: GeoDataFrame.to_parquet() does not pass through kwargs with partition_cols

### ISSUE THREAD

**Issue by dazza-codes** [geopandas/geopandas#2361]
- [ ] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

```
    gdf.to_parquet(report_path, compression=compression, partition_cols=partitions)
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/geopandas/geodataframe.py", line 1001, in to_parquet
    _to_parquet(self, path, compression=compression, index=index, **kwargs)
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/geopandas/io/arrow.py", line 248, in _to_parquet
    parquet.write_table(table, path, compression=compression, **kwargs)
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/pyarrow/parquet.py", line 2091, in write_table
    **kwargs) as writer:
  File "/opt/conda/envs/gis/lib/python3.7/site-packages/pyarrow/parquet.py", line 683, in __init__
    **options)
  File "pyarrow/_parquet.pyx", line 1430, in pyarrow._parquet.ParquetWriter.__cinit__
TypeError: __cinit__() got an unexpected keyword argument 'partition_cols'
```

#### Code Sample

Use any `GeoDataFrame.to_parquet()` with some partition_cols in the data frame.

#### Expected Output

A parquet dataset with partitions.  An example of a work around for this:

```python

            import pyarrow as pa
            import pyarrow.parquet as pq

            # This conversion of shapely geometry to WKT is reasonably fast with pygeos
            gdf["geometry"] = gdf.geometry.to_wkt()
            table = pa.Table.from_pandas(gdf)
            partitions = ["any-column-name-in-gdf"]
            pq.write_to_dataset(
                table, root_path="/tmp", compression="zstd", partition_cols=partitions,
            )
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0]
executable : /opt/conda/envs/gis/bin/python
machine    : Linux-5.4.0-100-generic-x86_64-with-debian-bullseye-sid

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /opt/conda/envs/gis/lib/python3.7/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /opt/conda/envs/gis/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.5
fiona      : 1.8.20
numpy      : 1.21.1
shapely    : 1.8.1
rtree      : 0.9.7
pyproj     : 2.6.1.post1
matplotlib : 3.5.1
mapclassify: None
geopy      : 2.2.0
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
geoalchemy2: 0.8.5
pyarrow    : 7.0.0
pygeos     : 0.12.0

</details>

**Comment by jankovicgd** [comment]
Bumping for visibility, as we are testing some of these features, and would help in optimization of some large datasets. 

Does anyone have any sample code using `pyarrow.parquet.write_to_dataset()` and `pyarrow.parquet.write_metadata()` successfully to write a partitioned dataset and store CRS information? Currently I am able to write a partitioned dataset but only without metadata. And it seems this issue causes some problems: https://github.com/apache/arrow/issues/31678

**Comment by martinfleis** [comment]
@jankovicgd you can check the implementation in https://github.com/geopandas/geopandas/pull/2808

**Comment by jankovicgd** [comment]
@martinfleis I think I also need some logic from [`_geopandas_to_arrow()`](https://github.com/tomalrussell/geopandas/blob/881b32b1cb129799ac81b0b283c047df9f50d111/geopandas/io/arrow.py#L239) since I am failing to read the dataset afterwards due to metadata. Thanks!

**Comment by martinfleis** [comment]
@jankovicgd that or a change in `read_parquet` to allow reading data without metadata. This was discussed during the last dev call and is also something we want to include as some other systems may be able to produce GeoParquet but not the metadata. Need to open a separate issue on that.

**Comment by alexgleith** [comment]
Just wanted to bump this and offer to test any draft implementation :-)

**Comment by zaneselvans** [comment]
This would be a super useful feature.  I'm currently running into an issue where I have no trouble writing a big GeoDataFrame out to Parquet (the compressed file is ~4GB), but then when I attempt to read from it and select just one year's worth of data:

```py
ba_counties = gpd.read_parquet(
    "../balancing_authority_geometry.parquet",
    filters=[("report_date", "==", pd.Timestamp("2020-01-01 00:00:00"))],
)
```
I get an `ArrowCapacityError`:
```
---------------------------------------------------------------------------
ArrowCapacityError                        Traceback (most recent call last)
File <timed exec>:1

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/geopandas/io/arrow.py:601, in _read_parquet(path, columns, storage_options, **kwargs)
    599 path = _expand_user(path)
    600 kwargs["use_pandas_metadata"] = True
--> 601 table = parquet.read_table(path, columns=columns, filesystem=filesystem, **kwargs)
    603 # read metadata separately to get the raw Parquet FileMetaData metadata
    604 # (pyarrow doesn't properly exposes those in schema.metadata for files
    605 # created by GDAL - https://issues.apache.org/jira/browse/ARROW-16688)
    606 metadata = None

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/pyarrow/parquet/core.py:3003, in read_table(source, columns, use_threads, metadata, schema, use_pandas_metadata, read_dictionary, memory_map, buffer_size, partitioning, filesystem, filters, use_legacy_dataset, ignore_prefixes, pre_buffer, coerce_int96_timestamp_unit, decryption_properties, thrift_string_size_limit, thrift_container_size_limit)
   2992         # TODO test that source is not a directory or a list
   2993         dataset = ParquetFile(
   2994             source, metadata=metadata, read_dictionary=read_dictionary,
   2995             memory_map=memory_map, buffer_size=buffer_size,
   (...)
   3000             thrift_container_size_limit=thrift_container_size_limit,
   3001         )
-> 3003     return dataset.read(columns=columns, use_threads=use_threads,
   3004                         use_pandas_metadata=use_pandas_metadata)
   3006 warnings.warn(
   3007     "Passing 'use_legacy_dataset=True' to get the legacy behaviour is "
   3008     "deprecated as of pyarrow 8.0.0, and the legacy implementation will "
   3009     "be removed in a future version.",
   3010     FutureWarning, stacklevel=2)
   3012 if ignore_prefixes is not None:

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/pyarrow/parquet/core.py:2631, in _ParquetDatasetV2.read(self, columns, use_threads, use_pandas_metadata)
   2623         index_columns = [
   2624             col for col in _get_pandas_index_columns(metadata)
   2625             if not isinstance(col, dict)
   2626         ]
   2627         columns = (
   2628             list(columns) + list(set(index_columns) - set(columns))
   2629         )
-> 2631 table = self._dataset.to_table(
   2632     columns=columns, filter=self._filter_expression,
   2633     use_threads=use_threads
   2634 )
   2636 # if use_pandas_metadata, restore the pandas metadata (which gets
   2637 # lost if doing a specific `columns` selection in to_table)
   2638 if use_pandas_metadata:

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/pyarrow/_dataset.pyx:556, in pyarrow._dataset.Dataset.to_table()

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/pyarrow/_dataset.pyx:3713, in pyarrow._dataset.Scanner.to_table()

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()

File ~/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()

ArrowCapacityError: array cannot contain more than 2147483646 bytes, have 2184927979
```

Which I think I could avoid if I were able to break the file up internally using Parquet row-groups defined by the `report_date` and/or the `balancing_authority_id_eia`.
