### ISSUE TITLE
BUG: After importing geopandas, any request performed with the requests library using a self-signed certificate leads to an SSL error

### ISSUE THREAD

**Issue by larsderidder** [geopandas/geopandas#2422]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

To run the below code, a API key for the specific API, plus its certificates are required. The API key I unfortunately cannot provide as it is a paid service. The required certificates however are found here: https://developers.kvk.nl/support/tls-certificate-chain-trust-instructions.

I do not mind rewriting this example to use a different API, but I couldn't find an open API with self-signed certificates (I suppose that is quite rare).

```python
import sys
import os
import requests
# Commenting out this line fixes the issue
import geopandas

URL_ZOEKEN = "https://api.kvk.nl/api/v1/zoeken"

CERT_FILE_NAME = "Staat_der_Nederlanden_Private_Root_CA_-_G1.crt"
"""Should be in the same folder as this file."""


def do_search(api_key):
    session: requests.Session = requests.Session()
    session.headers.update({"apikey": api_key})
    session.verify = os.path.join(
        os.path.abspath(os.path.dirname(__file__)), CERT_FILE_NAME
    )

    params = dict(
        straatnaam="Eemsgolaan",
        plaats="Groningen",
        pagina=1,
        aantal=1,
        type="hoofdvestiging,nevenvestiging",
    )
    response = session.get(URL_ZOEKEN, params=params)
    print(response.text)


if __name__ == '__main__':
    do_search(sys.argv[1])

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

When running the above code, providing a valid API key on the command line, I get the below error.

```
❯ python main.py <REDACTED>
Traceback (most recent call last):
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kvk.nl', port=443): Max retries exceeded with url: /api/v1/zoeken?straatnaam=Eemsgolaan&plaats=Groningen&pagina=1&aantal=1&type=hoofdvestiging%2Cnevenvestiging (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lars/workspace/geopandas-issue/main.py", line 31, in <module>
    do_search(sys.argv[1])
  File "/home/lars/workspace/geopandas-issue/main.py", line 26, in do_search
    response = session.get(URL_ZOEKEN, params=params)
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.kvk.nl', port=443): Max retries exceeded with url: /api/v1/zoeken?straatnaam=Eemsgolaan&plaats=Groningen&pagina=1&aantal=1&type=hoofdvestiging%2Cnevenvestiging (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

```

#### Expected Output

Without the import of geopandas, I get a normal JSON response, as expected from this API.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.9 (main, Jan 14 2022, 10:07:01)  [GCC 11.1.0]
executable : /home/lars/.virtualenvs/geopandas-issue/bin/python
machine    : Linux-5.10.105-1-MANJARO-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /usr/lib/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: /home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: /home/lars/.virtualenvs/geopandas-issue/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.4.2
fiona      : 1.8.21
numpy      : 1.22.3
shapely    : 1.8.1.post1
rtree      : None
pyproj     : 3.3.1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by larsderidder** [comment]
It appears the issue is caused by the fiona dependency of geopandas. I went on to try individual dependencies and only with fiona the issue appeared. I could downgrade fiona to 1.8.17 to "fix" this issue for me. I created an issue in the fiona repository with similar contents to this one, so I think this can be closed.

**Comment by jorisvandenbossche** [comment]
Thanks for opening the issue on the Fiona side!
