### ISSUE TITLE
DOC: readthedocs is failing

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2455]
RTD builds are failing for the last week (https://readthedocs.org/projects/geopandas/builds/17118809/) but I don't think we caused it.

```
mamba env create --quiet --name latest --file doc/environment.yml

Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/mambaforge-4.10.3-10/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/docs/.asdf/installs/python/mambaforge-4.10.3-10/lib/python3.9/site-packages/mamba/mamba.py", line 49, in <module>
    from mamba import repoquery as repoquery_api
  File "/home/docs/.asdf/installs/python/mambaforge-4.10.3-10/lib/python3.9/site-packages/mamba/repoquery.py", line 12, in <module>
    def _repoquery(query_type, q, pool, fmt=api.QueryFormat.JSON):
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'
```

I'll open an issue on the RTD tracker but we need to make sure this gets resolved before cutting 0.11.

**Comment by martinfleis** [comment]
Resolved by RTD support.
