### ISSUE TITLE
BUG: Maximum recursion depth reached in `_geodataframe_constructor_with_fallback`

### ISSUE THREAD

**Issue by benoit9126** [geopandas/geopandas#2486]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.geometry import Point, LineString

gs = gpd.GeoSeries(data=[LineString([(0,0), (1,0)]), LineString([(2,1), (3,1)])])
gdf= gpd.GeoDataFrame(data={"foo":[1,2]}, geometry=gs)
gdf.geometry.aggregate(
   {0: lambda x: Point(x.coords[0]), 1: lambda x: Point(x.coords[-1])}
).unstack(level=0)
```

#### Problem description

I have a geo data frame with LineString in the geometry columns. I try to make a data frame with two columns: the first one with the first point of each LineString and the second one, with the last one. The main point here is that I have reached a max recursion depth limit.

```python
Traceback (most recent call last):
  File "/home/benoit/.pyenv/versions/3.9.6/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/series.py", line 4157, in unstack
    return unstack(self, level, fill_value)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 490, in unstack
    return _unstack_extension_series(obj, level, fill_value)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 536, in _unstack_extension_series
    result = df.unstack(level=level, fill_value=fill_value)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/frame.py", line 8425, in unstack
    result = unstack(self, level, fill_value)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 478, in unstack
    return _unstack_frame(obj, level, fill_value=fill_value)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 503, in _unstack_frame
    return obj._constructor(mgr)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/geopandas/geodataframe.py", line 32, in _geodataframe_constructor_with_fallback
    df = GeoDataFrame(*args, **kwargs)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/geopandas/geodataframe.py", line 164, in __init__
    hasattr(self["geometry"].values, "crs")
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1412, in __getitem__
    result = super().__getitem__(key)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/frame.py", line 3473, in __getitem__
    return self._getitem_multilevel(key)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/frame.py", line 3560, in _getitem_multilevel
    result = self.reindex(columns=new_columns)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/util/_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/frame.py", line 4804, in reindex
    return super().reindex(**kwargs)
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/generic.py", line 4958, in reindex
    return self.copy()
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pandas/core/generic.py", line 6034, in copy
    return self._constructor(data).__finalize__(self, method="copy")
  File "/home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/geopandas/geodataframe.py", line 32, in _geodataframe_constructor_with_fallback
    df = GeoDataFrame(*args, **kwargs)

# And so on
```

#### Expected Output

I would have expected the same result as:

```python
pd.Series(gdf.geometry.aggregate(
   {0: lambda x: Point(x.coords[0]), 1: lambda x: Point(x.coords[-1])}
)).unstack(level=0)
```

As this workaround works, I don't expect a solution, but I wanted to report you this problem.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.6 (default, Aug 23 2021, 19:59:27)  [GCC 10.2.1 20210110]
executable : /home/benoit/.pyenv/versions/sirao_template_aode/bin/python
machine    : Linux-5.10.0-15-amd64-x86_64-with-glibc2.31

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: /home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: /home/benoit/.pyenv/versions/sirao_template_aode/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.0
pandas     : 1.4.3
fiona      : 1.8.21
numpy      : 1.23.0
shapely    : 1.8.2
rtree      : 1.0.0
pyproj     : 3.3.1
matplotlib : 3.5.2
mapclassify: None
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: 0.10.2
pyarrow    : None
pygeos     : 0.12.0

</details>

**Comment by m-richards** [comment]
Hi @benoit9126, thanks for the report (and minimal example to reproduce), I can confirm this is the case, and also that it is a regression introduced in 0.11. We'll add it to the list for a bug fix release.

**Comment by jorisvandenbossche** [comment]
A even a bit smaller reproducer (just to better understand where the issue is coming from, the minimal example to reproduce was already great!):

```
from shapely.geometry import Point
df = geopandas.GeoDataFrame({0: geopandas.GeoSeries([Point(0, 0), Point(1, 1)]), 1: geopandas.GeoSeries([Point(2, 2), Point(3, 3)])})
df.columns = pd.MultiIndex.from_product([["geometry"], [0, 1]])

In [4]: df
Out[4]: 
                  geometry                         
                         0                        1
0  POINT (0.00000 0.00000)  POINT (2.00000 2.00000)
1  POINT (1.00000 1.00000)  POINT (3.00000 3.00000)

In [5]: df.geometry
...
~/scipy/geopandas/geopandas/geodataframe.py in _geodataframe_constructor_with_fallback(*args, **kwargs)
     31     """
     32     # breakpoint()
---> 33     df = GeoDataFrame(*args, **kwargs)
     34     geometry_cols_mask = df.dtypes == "geometry"
     35     if len(geometry_cols_mask) == 0 or geometry_cols_mask.sum() == 0:

~/scipy/geopandas/geopandas/geodataframe.py in __init__(self, data, geometry, crs, *args, **kwargs)
    163             try:
    164                 if (
--> 165                     hasattr(self["geometry"].values, "crs")
    166                     and self["geometry"].values.crs
    167                     and crs

... last 9 frames repeated, from the frame below ...

~/scipy/geopandas/geopandas/geodataframe.py in __getitem__(self, key)
   1411         return a GeoDataFrame.
   1412         """
-> 1413         result = super().__getitem__(key)
   1414         geo_col = self._geometry_column_name
   1415         if isinstance(result, Series) and isinstance(result.dtype, GeometryDtype):

RecursionError: maximum recursion depth exceeded
```





While looking into this, I also noticed some other regressions (note that the below are not really "valid" GeoDataFrames, I accidentally created a GeoDataFrame with two object dtype columns (not geometry dtype), so this is very much a corner case):

```
from shapely.geometry import Point
df = geopandas.GeoDataFrame([[Point(0, 0), Point(1, 1)], [Point(2, 2), Point(3, 3)]])
df.columns = pd.MultiIndex.from_product([["geometry"], [0, 1]])

In [4]: df
Out[4]: 
      geometry             
             0            1
0  POINT (0 0)  POINT (1 1)
1  POINT (2 2)  POINT (3 3)

# recreating a GeoDataFrame from this fails (both worked on 0.10):
In [6]: geopandas.GeoDataFrame(df)
...
~/scipy/geopandas/geopandas/geodataframe.py in __init__(self, data, geometry, crs, *args, **kwargs)
    169                 ):
    170                     raise ValueError(crs_mismatch_error)
--> 171                 self["geometry"] = _ensure_geometry(self["geometry"].values, crs)
    172             except TypeError:
    173                 pass
...
ValueError: 'data' should be a 1-dimensional array of geometry objects.

In [7]: df[["geometry"]]
...
ValueError: 'data' should be a 1-dimensional array of geometry objects.

```

**Comment by jorisvandenbossche** [comment]
This patch seems to do the trick:

```diff
--- a/geopandas/geodataframe.py
+++ b/geopandas/geodataframe.py
@@ -148,7 +149,7 @@ class GeoDataFrame(GeoPandasBase, DataFrame):
             if crs is not None and data.crs != crs:
                 raise ValueError(crs_mismatch_error)
 
-        if geometry is None and "geometry" in self.columns:
+        if geometry is None and self.columns.nlevels == 1 and "geometry" in self.columns:
             # Check for multiple columns with name "geometry". If there are,
             # self["geometry"] is a gdf and constructor gets recursively recalled
             # by pandas internals trying to access this
```

So that we basically assume that if you have a MultiIndex, there is by definition never a column exactly called "geometry" (and thus we don't have to access that data to try to convert it to a array of geometry dtype). We actually already had a comment there about recursion.

This fixes my simpler case, and also seems to fix the original reported case.
