### ISSUE TITLE
BUG: Exporting df as a ESRI shapefile error: Object of type 'float' has no len()  

### ISSUE THREAD

**Issue by iamtekson** [geopandas/geopandas#2490]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
# Your code here
df.to_file(filename="test.shp", driver="ESRI Shapefile")
```

#### Problem description

The problem is occurred when the column name is an `float` type. Below is the Traceback,

```python
Traceback (most recent call last):
  File "/opt/sdss/django/sdss/exposure/views.py", line 353, in downloadExposureResult
    df.to_file(filename=shp_path, driver='ESRI Shapefile')
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1114, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/io/file.py", line 376, in _to_file
    if driver == "ESRI Shapefile" and any([len(c) > 10 for c in df.columns.tolist()]):
  File "/home/sdss/.virtualenvs/sdss/lib/python3.8/site-packages/geopandas/io/file.py", line 376, in <listcomp>
    if driver == "ESRI Shapefile" and any([len(c) > 10 for c in df.columns.tolist()]):
TypeError: object of type 'float' has no len()
```

#### Expected Output

It should write df into the shapefile.

#### Output of ``geopandas.show_versions()``
0.10.2

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by iamtekson** [comment]
Hi, I send the PR(#2491) for this issue. I hope it can be merged.

**Comment by martinfleis** [comment]
Neither Fiona or Pyogrio are able to write a file with integer column names, either due to a limitation of GDAL or the file formats. I tried many and all of them raise the same error. We should probably just ensure that the error is a bit more clear as `AttributeError: 'int' object has no attribute 'encode'` coming from both Fiona and pyogrio (meaning it comes likely from GDAL) is not great.

We can do a custom check on our side for integer column names and raise an informative error or cast them to string (not a fan).

**Comment by jorisvandenbossche** [comment]
> `AttributeError: 'int' object has no attribute 'encode'` coming from both Fiona and pyogrio (meaning it comes likely from GDAL)

Not actually from GDAL, but both fiona and pyogrio will call `col_name.encode("UTF-8")` on each column name to convert those to C strings (`char *`) because that is what GDAL requires for creating a field definition.

So I think the question for us is whether we want to leave this up to the user (but in that case give a more informative error message about column having to be strings) or cast non-string column names to string automatically on our side.

I am fine either way. Pandas is also a bit inconsistent on this matter. Some `to_..` methods do this automatically (eg `to_csv`, but of course that is a text-based format anyway, so every input value is converted to a string repr), while some other like `to_parquet` don't (I think in the idea to ensure a proper roundtrip can be done).

**Comment by martinfleis** [comment]
I am keep to check for that and raise an informative error, rather than casting it under the hood and having users complain that IO silently changed their data.

**Comment by jorisvandenbossche** [comment]
Sounds good to me
