### ISSUE TITLE
ENH: better user experience when fiona is not installed

### ISSUE THREAD

**Issue by rth** [geopandas/geopandas#2548]
As discussed in https://github.com/pyodide/pyodide/issues/1569#issuecomment-1242680806 it's possible to install geopandas in Pyodide, though fiona is for now not available there.

As @jorisvandenbossche mentioned in https://github.com/pyodide/pyodide/issues/1569#issuecomment-1242680271 loading GeoJSON 

> The only thing you can't use are the read_file/to_file functions. But you can load geojson using the GeoDataFrame.from_features if you pass it the dict from json.loads.

however, most people likely worn't be aware of it.

In the [Pyodide REPL](https://pyodide.org/en/stable/console.html),
```py
>>> import micropip
>>> await micropip.install(['pandas', 'shapely', 'pyproj'])
>>> await micropip.install('geopandas', deps=False)
>>> import geopandas as gpd
>>> from pyodide.http import pyfetch
>>> res = await pyfetch("https://development-data-hub-s3-public.s3.amazonaws.com/ddhfiles/144828/africawaterbody.geojson)
>>> data = await res.json()
>>> df = gpd.GeoDataFrame.from_features(data)
>>> df
                                              geometry  ...  Shape_len
0    MULTIPOLYGON (((9.72104 37.12155, 9.71645 37.1...  ...   0.432045
1    MULTIPOLYGON (((8.32990 36.88232, 8.32359 36.8...  ...   0.110025
2    MULTIPOLYGON (((8.38329 36.82655, 8.35944 36.8...  ...   0.174179
3    MULTIPOLYGON (((10.25552 36.77393, 10.25066 36...  ...   0.211722
```

Though indeed, using read_file fails with,
```py
>>> import json
>>> with open('/tmp/data.geojson', 'w') as fh:
...     json.dump(data, fh)
>>> gpd.GeoDataFrame.from_file('/tmp/data.geojson')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/geopandas/geodataframe.py", line 569, in from_file
    return geopandas.io.file._read_file(filename, **kwargs)
  File "/lib/python3.10/site-packages/geopandas/io/file.py", line 236, in _read_file
    engine = _check_engine(engine, "'read_file' function")
  File "/lib/python3.10/site-packages/geopandas/io/file.py", line 107, in _check_engine
    raise ImportError(
ImportError: The 'read_file' function requires the 'pyogrio' or 'fiona' package, but neither is installed or imports correctly.
Importing fiona resulted in: No module named 'fiona'
Importing pyogrio resulted in: No module named 'pyogrio'
```

Maybe it would be useful to have a fallback to plain json parser for `.geojson` in case none of those backends are installed (or at least indicate that it can be parsed manually with `GeoDataFrame.from_features`)?

**Comment by martinfleis** [comment]
Hi, this is actually on the roadmap. The aim is to have pure python IO for GeoJSON, SHP (#1580) and GPKG (https://github.com/geopandas/pgpkg) exposed in `read_file` and `to_file` when you don't want or cannot install GDAL, like in this case. I think that with the boom of WASM, it may be more relevant now.
