### ISSUE TITLE
BUG: Crash (access violation) running `GeoDataFrame.dissolve` only on Windows Server 2022 + Python 3.8/3.9

### ISSUE THREAD

**Issue by l0b0** [geopandas/geopandas#2766]
Disclaimer: I don't have a Windows machine at work to test on (only GitHub runners) and I don't know enough about Geopandas, GDAL, Jupyter, Windows memory models, etc. to reduce this to a minimal example in a reasonable amount of time. If that means this issue will be closed, then that's OK, and sorry if this is considered wasting your time - I'll simply not support Windows for the time being. Others at Toitū Te Whenua LINZ have expressed an interest in getting GDAL etc. running "properly" in Windows without installing things like QGIS, so the motivation goes beyond just "I want to support as many platforms as possible".

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of geopandas.
- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

[This branch](https://github.com/linz/emergency-management-tools/pull/120) demonstrates the issue. [The code](https://gist.github.com/l0b0/867cc2e8c08380b0be7a097229bab818#file-sentinel2_water_extraction-py) has been extracted with `jupyter nbconvert --to=script sentinel2_water_extraction.ipynb`.

#### Problem description

This seems to be the relevant part of the [full build log](https://gist.github.com/l0b0/867cc2e8c08380b0be7a097229bab818#file-build-log):

```text
Traceback (most recent call last):
  File "C:\Miniconda\envs\__setup_conda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Miniconda\envs\__setup_conda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\envs\__setup_conda\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\jupyter_core\application.py", line 276, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\exporters\exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\exporters\exporter.py", line 207, in from_file
    return self.from_notebook_node(
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\exporters\notebook.py", line 35, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\exporters\exporter.py", line 147, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\exporters\exporter.py", line 342, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\preprocessors\execute.py", line 91, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbconvert\preprocessors\execute.py", line 112, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\jupyter_core\utils\__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Miniconda\envs\__setup_conda\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Miniconda\envs\__setup_conda\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbclient\client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Miniconda\envs\__setup_conda\lib\site-packages\nbclient\client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
SIEVE_THRESHOLD = 10

for image_with_water in IMAGES:
    # Mask out all values below the mndwi threshold (these are not water)
    water_mask = np.ma.masked_less(  # type: ignore[no-untyped-call]
        image_with_water["mndwi"], MNDWI_THRESHOLD
    )

    # Extract the polygons from the mask
    water_polygons = rasterio.features.shapes(
        source=water_mask.astype("uint8"),
        transform=image_with_water["transform_window"],
    )

    # Add all polygons to the list
    water_polygons = list(water_polygons)

    # Extract the polygon coordinates and values from the list
    polygons = [polygon for polygon, value in water_polygons]
    values = [str(int(value)) for polygon, value in water_polygons]

    # Convert polygons into a shapely.shape
    polygons = [shape(polygon) for polygon in polygons]

    # Create a geopandas dataframe populated with the polygon shapes
    water_geodataframe = gpd.GeoDataFrame(
        {"is_water": values, "geometry": polygons}, crs=image_with_water["src_crs"]
    )

    # Dissolve all records into two records. is water / is not water
    is_water = water_geodataframe.dissolve(by="is_water")

    # Select only the water records
    water = is_water.query("is_water=='0'")

    # Export the polygons
    water.to_file(
        os.path.join(
            OUTPUT_DIRECTORY, f"water_mndwi_{image_with_water['image_id']}.shp"
        )
    )

    # Export the accompanying Sentinel-2 image
    export_raster(image_with_water)

    # Export working steps if desired
    image_with_water["water"] = water
    image_with_water["water_mask"] = water_mask
    if len(water.area) == 1:
        image_with_water["area"] = water.area[0] / 1000000  # in km2
    else:
        image_with_water["area"] = 0
```

and

```text
OSError: exception: access violation writing 0x0000000000001101
```

#### Output of ``geopandas.show_versions()``

<details>
SYSTEM INFO
-----------
python     : 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
executable : C:\Miniconda\envs\__setup_conda\python.exe
machine    : Windows-10-10.0.20348-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.5.2
GDAL data dir: C:\Miniconda\envs\__setup_conda\lib\site-packages\fiona\gdal_data
PROJ       : 9.1.0
PROJ data dir: C:\Miniconda\envs\__setup_conda\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.23.5
pandas     : 1.3.5
pyproj     : 3.4.0
shapely    : 1.8.5.post1
fiona      : 1.8.22
geoalchemy2: None
geopy      : None
matplotlib : 3.6.3
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None
</details>

**Comment by martinfleis** [comment]
GeoPandas supports windows, that is not an issue. You seem to have some installation issue in here. It comes from shapely, so the first thing I would recommend is to install the latest shapely (2.0) which completely rewrites the interface with GEOS and the line causing trouble here is not present anymore.

In your workflow, you should also install geopandas and its dependencies with conda, not poetry. Installing from PyPI on Windows is notoriously problematic (while it is getting better with pyogrio and shapely2).
