### ISSUE TITLE
BUG: Can't write a GeoDataframe to a Spatialite database

### ISSUE THREAD

**Issue by Cabanon** [geopandas/geopandas#2799]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

In order to run this code you need to install spatialite with `sudo apt-get install libsqlite3-mod-spatialite` and to `pip install -r` the following file

```
geopandas
sqlalchemy
geoalchemy2 @ git+https://github.com/geoalchemy/geoalchemy2
```

```python
import os

import geopandas as gpd
from sqlalchemy import create_engine
from sqlalchemy.event import listen
from geoalchemy2 import load_spatialite

SQLALCHEMY_DATABASE_URL = "sqlite:///./gis.db"
os.environ["SPATIALITE_LIBRARY_PATH"] = "/usr/lib/x86_64-linux-gnu/mod_spatialite.so"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False}
)
listen(engine, "connect", load_spatialite)

path_to_data = gpd.datasets.get_path("nybb")
gdf = gpd.read_file(path_to_data)
gdf.to_postgis("locations", engine, schema='main', if_exists="replace")
```

#### Problem description

The [to_postgis](https://github.com/geopandas/geopandas/blob/00e3748c987f5b9a14b5df5233421710811d75bf/geopandas/geodataframe.py#L1888) function of geopandas fails to write a GeoDataframe to a Spatialite database.

When omitting the `schema='main'` parameter the command fail with the following traceback: 

```
Traceback (most recent call last):
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: unknown database public
```

This is because the [_write_postgis](https://github.com/geopandas/geopandas/blob/00e3748c987f5b9a14b5df5233421710811d75bf/geopandas/io/sql.py#L337) function assume that the schema name is 'public' but it doesn't exist in SQLite so I tried with 'main' (which is the default schema/database in SQLite) but an other error happened for which a fix have been made on the geoalchemy master branch so I have pip installed it from github but now I still have an error on the geopandas side.

It seems to be linked to the [_psql_insert_copy](https://github.com/geopandas/geopandas/blob/00e3748c987f5b9a14b5df5233421710811d75bf/geopandas/io/sql.py#L318)  function

Here is the traceback :

```
Traceback (most recent call last):
  File "/home/mathias/geopandas_issue/issue.py", line 18, in <module>
    gdf.to_postgis("locations", engine, schema='main', if_exists="replace")
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1931, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/geopandas/io/sql.py", line 445, in _write_postgis
    gdf.to_sql(
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1738, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 1325, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 946, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/geopandas/io/sql.py", line 330, in _psql_insert_copy
    with dbapi_conn.cursor() as cur:
AttributeError: __enter__
```
I have tried to troubleshoot this error without any success, can anyone help me fix this ?

#### Expected Output

I expect geopandas to be able to write to a Spatialite database

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
executable : /home/mathias/geopandas_issue/venv/bin/python
machine    : Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.5.3
GDAL data dir: /home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 9.1.0
PROJ data dir: /home/mathias/geopandas_issue/venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.24.2
pandas     : 1.5.3
pyproj     : 3.4.1
shapely    : 2.0.1
fiona      : 1.9.1
geoalchemy2: 0.13.2.dev5+gfd3fce0
geopy      : None
matplotlib : None
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None

</details>

**Comment by m-richards** [comment]
Hi @Cabanon, thanks for reporting this, I'm also able to replicate it. Taking a look at the implementation and tests we have for to_postgis, it seems its never actually been able to write to spatialite (although read postgis can read from spatialite).

First I'd like to share a workaround for this specific issue - which is to not use geopandas/ geoalchemy for the writing at all. I've done this in the past in a context where I wasn't able to have geoalchemy as a dependency. Unfortunately I no longer have access to the code for that, but I think I've got something rather rough that seems to work (but please test it more rigorously!) using your snippet as a starting point:
```python
import os
import sqlite3

import geopandas as gpd
from sqlalchemy import create_engine
from sqlalchemy.event import listen
# from geoalchemy2 import load_spatialite

dll_dir = r"C:\Users\Matt\Downloads\mod_spatialite-5.0.1-win-amd64\mod_spatialite-5.0.1-win-amd64"
os.environ["PATH"] =dll_dir + ";" + os.environ['PATH']

def engine_listener(dbapi_conn, _connection_record):
    dbapi_conn.enable_load_extension(True)
    dbapi_conn.load_extension("mod_spatialite")

db_path = "out3.spatialite"
with sqlite3.connect(db_path) as conn:
    conn.enable_load_extension(True)
    conn.load_extension("mod_spatialite")
    conn.execute("SELECT InitSpatialMetaData(1);")

engine = create_engine(f"sqlite:///{db_path}")
listen(engine, "connect", engine_listener)

conn = engine.connect()
TABLE_NAME = "locations"

path_to_data = gpd.datasets.get_path("nybb")
gdf = gpd.read_file(path_to_data)
df = gdf.drop(columns=['geometry']).assign(geometry=gdf.geometry.to_wkb())

geom_col_name = gdf.geometry.name
crs = gdf.geometry.crs
srid = crs.to_epsg()

df.to_sql(TABLE_NAME, conn, if_exists="replace", index=False)
conn.execute(f"UPDATE '{TABLE_NAME}' SET {geom_col_name}=GeomFromWKB({geom_col_name}, {srid});")
conn.execute(
    "SELECT RecoverGeometryColumn('{tb}', '{geom_col}', {sr}, '{gt}', 'XY');".format(
        tb=TABLE_NAME, geom_col=geom_col_name, sr=srid, gt="MULTIPOLYGON"
    )
)
```
It's not generic, and as I said it's been a while since I dealt with geodataframes -> spatialite so there might be some redundancy/ edge cases as well, but hopefully it's still a starting point. 

As to why there are issues with the geopandas implementation, we should actually allow `schema=None` for sqlite, and 
https://github.com/geopandas/geopandas/blob/00e3748c987f5b9a14b5df5233421710811d75bf/geopandas/io/sql.py#L318-L334
fails because it this case it receives an sqlite3 connection and not a sqlachemy cursor which I presume it's expecting.
Locally however if I replace the method in `to_sql` with `"multi"` or `None`, this appears to work, but the geometry column is written as nulls... so more investigation required.

**Comment by theroggy** [comment]
I'm not sure there is a specific reason why you use `to_postgis()`, but an alternative could be to use `to_file()` like this:

```
import geopandas as gpd

path_to_data = gpd.datasets.get_path("nybb")
gdf = gpd.read_file(path_to_data)
gdf.to_file("gid.db", driver="SQLite", layer="locations", SPATIALITE=True)
```

If speed has some importance, you can install the optional pyogrio package and add parameter `engine="pyogrio"` to to_file(), this will be a lot faster for larger datasets.

**Comment by m-richards** [comment]
> I'm not sure there is a specific reason why you use `to_postgis()`, but an alternative could be to use `to_file()` like this:

Thanks @theroggy for reminding me this now works. I think historically didn't support and or expose spatialite drivers, but clearly now it does. I definitely think it's worth noting that this is possible in the documentation of read_postgis/ to_postgis as there are lots of old, out of date tutorials of workarounds to write dataframes to spatialite.
