### ISSUE TITLE
conda install breaking fiona in development environments

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#286]
The `conda` install of fiona is broken in anaconda development environments, so `conda install -c ioos geopandas` (which reloads fiona from conda even if it's already installed correctly) don't work. 

Replicable:

     conda create --name test_env2  python=3.4
     source activate test_env2
     pip install fiona 

Now you can tests with `python` then `import fiona` -- no problems. 

Then run: 

     conda install -c ioos geopandas

And try again -- `import fiona` breaks with this error:

    Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import fiona
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/Nick/anaconda/envs/test_env5/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
        from fiona.collection import Collection, BytesCollection, vsi_path
      File "/Users/Nick/anaconda/envs/test_env5/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
        from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: dlopen(/Users/Nick/anaconda/envs/test_env5/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/    lib/libgif.4.1.6.dylib
      Referenced from: /Users/Nick/anaconda/envs/test_env5/lib/libgdal.1.dylib
      Reason: image not found

So I don't think we can rely on conda to install fiona. `pip install fiona` seems to work fine.

**Comment by nickeubank** [comment]
Oops -- dup of #237
