### ISSUE TITLE
BUG: ANSI and UTF-8 in same file

### ISSUE THREAD

**Issue by sehHeiden** [geopandas/geopandas#3016]
I had the problem for some files, that write the file with geopandas to a geopackage and than open it in the next programm with geopandas I get the utf-8 error:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 25: invalid continuation byte

 I had no problem with QGIS to open the file.

I tried both engines. The error ocurred in both. I set the encoding to utf-8 for writing AND opening. Same error.
I changed the format from geopckage to geojson (without setting the encoding) and opened in Notepad++
The letter Ä or ä was encoded ANSI in column name and utf-8 in the values.

For geojson I set encoding to utf-8 and everything works.

I installed geopandas on the same day 2023-09-13 from pip on windows using a env.

SYSTEM INFO
-----------
python     : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
executable : D:\GIT\ECKE\venv\Scripts\python.exe
machine    : Windows-10-10.0.19045-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.6.4
GDAL data dir: D:\GIT\ECKE\venv\lib\site-packages\fiona\gdal_data
PROJ       : 9.2.1
PROJ data dir: D:\GIT\ECKE\venv\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.25.2
pandas     : 1.5.3
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.9.4.post1
geoalchemy2: None
geopy      : None
matplotlib : 3.7.3
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None

**Comment by m-richards** [comment]
Hi @sehHeiden, it is very hard for us to action this with neither a sample file nor a stack trace. If you could provide more information, that would help us investigate. You might like to read https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for some suggestions on how to provide a helpful bug report.

**Comment by sehHeiden** [comment]
Sorry, 

 but I cannot provide you with file. So I probably cannot repodue the problem with minimal code.

I paste the trace from the error message, that I get, when opening a geojson in program *B*, that I have just written with program *A* without specifing the enconding.

> Traceback (most recent call last):
>   File "C:\Users\remote\anaconda3\envs\ECKE\lib\site-packages\geopandas\io\file.py", line 351, in _read_file_fiona
>     columns = list(features.schema["properties"])
>   File "C:\Users\remote\anaconda3\envs\ECKE\lib\site-packages\fiona\collection.py", line 208, in schema
>     self._schema = self.session.get_schema()
>   File "fiona\ogrext.pyx", line 675, in fiona.ogrext.Session.get_schema
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 25: invalid continuation byte
> python-BaseException

**Comment by jorisvandenbossche** [comment]
Could you also show the error traceback when using the pyogrio engine?

> I cannot provide you with file. So I probably cannot repodue the problem with minimal code.

It's certainly understandable that you cannot just share the file, but that doesn't have to meant that you cannot reproduce it with minimal code! Not necessarily easy, but some steps that could help to reduce the example until a point you can share it:

* If you only take the first few rows of the file, and then write+read it, do you get the same? If not with the first few rows, can you try to find the rows that cause the error (eg start with taking the first or second half of all rows, does it still error, and then gradually reduce the size)
* Same thing for the columns: do you need all columns in the file, or only a subset or specific column?
* Is it related to the data in your columns, or related to your column names? (eg when using different (dummy) column names with the same data, do you still see the error. Or when using the same column names, but with some random float data, do you still see the error?)
* Once you have it boiled down to a smaller subset of your data, at that point it might be possible to replace the data with some random data (but that has the same data types or other characteristics to keep reproducing it) so that you can actually share it.
