### ISSUE TITLE
BUG: TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.

### ISSUE THREAD

**Issue by nerdykamil** [geopandas/geopandas#3054]
- [Yes ] I have checked that this issue has not already been reported.

- [Yes ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import geopandas as gpd
from shapely.geometry import Polygon
polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),
                              Polygon([(2,2), (4,2), (4,4), (2,4)])])
polys2 = gpd.GeoSeries([Polygon([(1,1), (3,1), (3,3), (1,3)]),
                              Polygon([(3,3), (5,3), (5,5), (3,5)])])
df1 = gpd.GeoDataFrame({'geometry': polys1, 'df1_data':[1,2]})
df2 = gpd.GeoDataFrame({'geometry': polys2, 'df2_data':[1,2]})

gpd.overlay(df1, df2, how='intersection')


#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output

df1_data  df2_data                                           geometry
0         1         1  POLYGON ((2.00000 2.00000, 2.00000 1.00000, 1....
1         2         1  POLYGON ((2.00000 2.00000, 2.00000 3.00000, 3....
2         2         2  POLYGON ((4.00000 4.00000, 4.00000 3.00000, 3....

#### Output of ``geopandas.show_versions()``

<details>
SYSTEM INFO
-----------
python     : 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]
executable : C:\software\anaconda3\envs\hayat\python.exe
machine    : Windows-10-10.0.22621-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.12.0
GEOS lib   : None
GDAL       : 3.7.2
GDAL data dir: None
PROJ       : 9.2.1
PROJ data dir: C:\software\anaconda3\envs\hayat\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.0
numpy      : 1.25.1
pandas     : 2.0.3
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.9.4
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : 0.14
pyogrio    : None
psycopg2   : 2.9.6 (dt dec pq3 ext lo64)
pyarrow    : 13.0.0
rtree      : 1.0.1

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by jorisvandenbossche** [comment]
For me this seems to work fine:

```
In [3]: import geopandas as gpd
   ...: from shapely.geometry import Polygon
   ...: polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),
   ...:                               Polygon([(2,2), (4,2), (4,4), (2,4)])])
   ...: polys2 = gpd.GeoSeries([Polygon([(1,1), (3,1), (3,3), (1,3)]),
   ...:                               Polygon([(3,3), (5,3), (5,5), (3,5)])])
   ...: df1 = gpd.GeoDataFrame({'geometry': polys1, 'df1_data':[1,2]})
   ...: df2 = gpd.GeoDataFrame({'geometry': polys2, 'df2_data':[1,2]})
   ...: 
   ...: gpd.overlay(df1, df2, how='intersection')
Out[3]: 
   df1_data  df2_data                                           geometry
0         1         1  POLYGON ((2.00000 2.00000, 2.00000 1.00000, 1....
1         2         1  POLYGON ((2.00000 2.00000, 2.00000 3.00000, 3....
2         2         2  POLYGON ((4.00000 4.00000, 4.00000 3.00000, 3....
```

@nerdykamil can you show the full error traceback that you get?

**Comment by adikte** [comment]
I got exactly the same problem with : 
`import geopandas as gpd
from shapely.geometry import Polygon
polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),
                              Polygon([(2,2), (4,2), (4,4), (2,4)])])
polys2 = gpd.GeoSeries([Polygon([(1,1), (3,1), (3,3), (1,3)]),
                              Polygon([(3,3), (5,3), (5,5), (3,5)])])
df1 = gpd.GeoDataFrame({'geometry': polys1, 'df1_data':[1,2]})
df2 = gpd.GeoDataFrame({'geometry': polys2, 'df2_data':[1,2]})
gpd.overlay(df1, df2, how='intersection')`

The full error trace back is : 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 11, in <module>
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\geopandas\tools\overlay.py", line 321, in overlay
    result = _overlay_intersection(df1, df2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\geopandas\tools\overlay.py", line 31, in _overlay_intersection
    idx1, idx2 = df2.sindex.query(df1.geometry, predicate="intersects", sort=True)
                 ^^^^^^^^^^
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\geopandas\base.py", line 3548, in sindex
    return self.geometry.values.sindex
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\geopandas\array.py", line 316, in sindex
    self._sindex = _get_sindex_class()(self._data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\geopandas\sindex.py", line 741, in __init__
    non_empty[mod.is_empty(non_empty)] = None
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\shapely\decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrien\rdoenv311\Lib\site-packages\shapely\predicates.py", line 166, in is_empty
    return lib.is_empty(geometry, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.

**Comment by Orkunnnn** [comment]
Works for me.

`
SYSTEM INFO
-----------
python     : 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
executable : c:\Users\orkun\miniconda3\envs\pythonProject\python.exe
machine    : Windows-10-10.0.19045-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.12.0
GEOS lib   : None
GDAL       : 3.7.2
GDAL data dir: None
PROJ       : 9.3.0
PROJ data dir: c:\Users\orkun\miniconda3\envs\pythonProject\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.0
numpy      : 1.26.0
pandas     : 2.1.1
pyproj     : 3.6.1
shapely    : 2.0.1
fiona      : 1.9.4
geoalchemy2: None
geopy      : None
matplotlib : 3.8.0
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1
`

**Comment by m-richards** [comment]
It seems like this is an environment issue, installing the packages from show versions gives the following mamba solver error: 
```
│  ├─ pygeos 0.14 would require
│  │  └─ geos >=3.11.2,<3.11.3.0a0 , which conflicts with any installable versions previously reported;
```
(Although if I install without pygeos and then pip install pygeos the snippet works fine, so pygeos itself is not necessarily the root cause)
