### ISSUE TITLE
BUG: implementation under pandas 15.2 not preserving geometry attribute under loc

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#324]
We could fix, or we could just drop support for 15.2...

```
os.chdir('/users/nick/github/geopandas/geopandas/tests')
from util import unittest, download_nybb

nybb_filename, nybb_zip_path = download_nybb()
polydf = read_file(nybb_zip_path, vfs='zip://' + nybb_filename)[['geometry', 'BoroName', 'BoroCode']]
polydf = polydf.rename(columns={'geometry':'myshapes'})
polydf = polydf.set_geometry('myshapes')

# subset
manhattan_bronx = polydf.loc[3:4,]


manhattan_bronx.geometry
Traceback (most recent call last):

  File "<ipython-input-8-3803180ba64f>", line 1, in <module>
    manhattan_bronx.geometry

  File "/Users/Nick/anaconda/envs/py2_gp/lib/python2.7/site-packages/pandas/core/generic.py", line 1947, in __getattr__
    (type(self).__name__, name))

AttributeError: 'GeoDataFrame' object has no attribute 'geometry'
```

I assume not noticed because most tests still work if geometry column named geometry (not to harp, but #294)...

**Comment by jorisvandenbossche** [comment]
Closed by #413
