### ISSUE TITLE
BUG: `pyogrio` doesn't like io.BytesIO?

### ISSUE THREAD

**Issue by bretttully** [geopandas/geopandas#3260]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of geopandas.
- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import io

from shapely import Polygon

import geopandas as gpd
from geopandas.testing import assert_geodataframe_equal

gpd.options.io_engine = "pyogrio"

data = gpd.GeoDataFrame(
    [
        {"foo": 1, "bar": "a", "geometry": Polygon([(0, 0), (0, 1), (1, 1)])},
        {"foo": 2, "bar": "b", "geometry": Polygon([(0, 0), (0, 2), (2, 2)])},
        {"foo": 3, "bar": "c", "geometry": Polygon([(0, 0), (0, 3), (3, 3)])},
    ],
    geometry="geometry",
    crs="EPSG:4326",
)


with io.BytesIO() as stream:
    data.to_file(stream, layer="geometry", driver="GPKG")
    bytestr = stream.getvalue()


with io.BytesIO(bytestr) as stream:
    data1 = gpd.read_file(stream, driver="GPKG")


assert_geodataframe_equal(data, data1)

```

#### Problem description

Fails with the following error

```
/Users/brett.tully/micromamba/envs/geopandas_dev/lib/python3.12/site-packages/pyogrio/raw.py:530: RuntimeWarning: The filename extension should be 'gpkg' instead of '' to conform to the GPKG specification.
  ogr_write(
Traceback (most recent call last):
  File "/Users/brett.tully/Development/datascience/geopandas/tmp.py", line 29, in <module>
    data1 = gpd.read_file(stream, driver="GPKG")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brett.tully/Development/datascience/geopandas/geopandas/io/file.py", line 280, in _read_file
    return _read_file_pyogrio(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/brett.tully/Development/datascience/geopandas/geopandas/io/file.py", line 533, in _read_file_pyogrio
    return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brett.tully/micromamba/envs/geopandas_dev/lib/python3.12/site-packages/pyogrio/geopandas.py", line 239, in read_dataframe
    result = read_func(
             ^^^^^^^^^^
  File "/Users/brett.tully/micromamba/envs/geopandas_dev/lib/python3.12/site-packages/pyogrio/raw.py", line 194, in read
    result = ogr_read(
             ^^^^^^^^^
  File "pyogrio/_io.pyx", line 1124, in pyogrio._io.ogr_read
  File "pyogrio/_io.pyx", line 167, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: '/vsimem/0bb337302a3e416585c0713adbddd5cf' not recognized as a supported file format. It might help to specify the correct driver explicitly by prefixing the file path with '<DRIVER>:', e.g. 'CSV:path'.
```

#### Output of ``geopandas.show_versions()``

<details>

```
SYSTEM INFO
-----------
python     : 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]
executable : /Users/brett.tully/micromamba/envs/geopandas_dev/bin/python
machine    : macOS-14.3.1-arm64-arm-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.12.1
GEOS lib   : None
GDAL       : 3.8.3
GDAL data dir: /Users/brett.tully/micromamba/envs/geopandas_dev/share/gdal/
PROJ       : 9.3.1
PROJ data dir: /Users/brett.tully/micromamba/envs/geopandas_dev/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.0+118.ga4a14c5
numpy      : 1.26.3
pandas     : 2.2.0
pyproj     : 3.6.1
shapely    : 2.0.2
pyogrio    : 0.7.2
geoalchemy2: None
geopy      : None
matplotlib : 3.8.2
mapclassify: None
fiona      : 1.9.5
psycopg    : None
psycopg2   : None
pyarrow    : 14.0.2
```

</details>

**Comment by bretttully** [comment]
It actually looks like the error might be on the save, not on the read. The following fails.

```python
import io
import os
from pathlib import Path

import pyogrio
import pyogrio.raw
from shapely import Polygon

import geopandas as gpd
from geopandas.testing import assert_geodataframe_equal

os.environ["PYOGRIO_USE_ARROW"] = "1"
gpd.options.io_engine = "pyogrio"
gpd.show_versions()

data = gpd.GeoDataFrame(
    [
        {"foo": 1, "bar": "a", "geometry": Polygon([(0, 0), (0, 1), (1, 1)])},
        {"foo": 2, "bar": "b", "geometry": Polygon([(0, 0), (0, 2), (2, 2)])},
        {"foo": 3, "bar": "c", "geometry": Polygon([(0, 0), (0, 3), (3, 3)])},
    ],
    geometry="geometry",
    crs="EPSG:4326",
)

outpath = Path("tmp.gpkg")
if outpath.exists():
    outpath.unlink()
data.to_file(outpath, layer="geometry", driver="GPKG")
assert outpath.exists()
bytestr_from_file = outpath.read_bytes()

with io.BytesIO() as stream:
    data.to_file(stream, layer="geometry", driver="GPKG")
    bytestr = stream.getvalue()
assert bytestr == bytestr_from_file, f"{len(bytestr)=}\n{len(bytestr_from_file)=}"
```

**Comment by m-richards** [comment]
Thanks @bretttully for the report, this is currently the case, see https://github.com/geopandas/pyogrio/issues/249 (and discussion in https://github.com/geopandas/geopandas/issues/2875). We should note this as a difference between fiona and pyogrio that could break people in 1.0

**Comment by bretttully** [comment]
Oh, thanks @m-richards -- that would be a fairly large regression for us... We could work around by writing to a temp file and then reading to bytes back in, but that wouldn't be great.

**Comment by martinfleis** [comment]
Thanks @bretttully, this is a good feedback to have! I suppose you're not the only one using BytesIO as intermediate files.

@jorisvandenbossche @brendan-ward @theroggy what is the feasibility of getting this to pyogrio 0.8 before geopandas 1.0 lands?

**Comment by brendan-ward** [comment]
I've been looking into this based on how it is implemented in Fiona / rasterio and working toward a potential PR.  Not sure about the timing because there are some complexities here to work out (GPKG append / add layers to memory stream).  Will continue the discussion on the pyogrio side.

**Comment by martinfleis** [comment]
@bretttully can you post the output of `geopandas.show_versions()` of an environment where this actually works, when using Fiona?

**Comment by bretttully** [comment]
```
SYSTEM INFO
-----------
python     : 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
executable : /opt/conda/bin/python
machine    : Linux-4.14.336-257.562.amzn2.x86_64-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.12.1
GEOS lib   : None
GDAL       : 3.8.4
GDAL data dir: /opt/conda/share/gdal
PROJ       : 9.3.1
PROJ data dir: /opt/conda/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.3
numpy      : 1.26.4
pandas     : 2.2.2
pyproj     : 3.6.1
shapely    : 2.0.4
fiona      : 1.9.6
geoalchemy2: None
geopy      : 2.4.1
matplotlib : 3.8.4
mapclassify: 2.6.1
pygeos     : None
pyogrio    : 0.7.2
psycopg2   : 2.9.9 (dt dec pq3 ext lo64)
pyarrow    : 13.0.0
rtree      : 1.2.0
```

Code:

<details>

```python
import io
from pathlib import Path

import geopandas as gpd
from geopandas.testing import assert_geodataframe_equal
from shapely import Polygon

gpd.show_versions()

data = gpd.GeoDataFrame(
    [
        {"foo": 1, "bar": "a", "geometry": Polygon([(0, 0), (0, 1), (1, 1)])},
        {"foo": 2, "bar": "b", "geometry": Polygon([(0, 0), (0, 2), (2, 2)])},
        {"foo": 3, "bar": "c", "geometry": Polygon([(0, 0), (0, 3), (3, 3)])},
    ],
    geometry="geometry",
    crs="EPSG:4326",
)

outpath = Path("tmp.gpkg")
if outpath.exists():
    outpath.unlink()
data.to_file(outpath, layer="geometry", driver="GPKG")
assert outpath.exists()
bytestr_from_file = outpath.read_bytes()

with io.BytesIO() as stream:
    data.to_file(stream, layer="geometry", driver="GPKG")
    bytestr = stream.getvalue()
assert len(bytestr) == len(bytestr_from_file), f"{len(bytestr)=} != {len(bytestr_from_file)=}"


with io.BytesIO(bytestr) as stream:
    data2 = gpd.read_file(stream, driver="GPKG")
assert_geodataframe_equal(data, data2)
```

</details>

**Comment by bretttully** [comment]
Note the change of `assert bytestr == bytestr_from_file` to `assert len(bytestr) == len(bytestr_from_file)` -- I forgot sqlite puts the timestamp in the file.

**Comment by jorisvandenbossche** [comment]
Thanks @bretttully I can indeed reproduce that, it works with fiona (both with released geopandas as with geopandas main), and as we know it does not yet work with pyogrio (https://github.com/geopandas/pyogrio/issues/249)

From a quick test, current fiona does not allow to append (`mode="a"`) for writing to a file-like object. 

Fiona allows you to write for a multi-file driver like Shapefile, but then reading the resulting bytes doesn't work (at least not easily by just passing a stream):

```
In [13]: with io.BytesIO() as stream:
    ...:     data.to_file(stream, driver="ESRI Shapefile", engine="fiona")
    ...:     bytestr = stream.getvalue()
    ...: 

In [14]: with io.BytesIO(bytestr) as stream:
    ...:     data2 = gpd.read_file(stream, engine="fiona")
    ...: 
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
...

File fiona/ogrext.pyx:143, in fiona.ogrext.gdal_open_vector()

DriverError: '/vsimem/9d4fe4810f7c446898a9875a739fbebf' not recognized as a supported file format.
```

**Comment by brendan-ward** [comment]
This is now implemented in pyogrio 0.8.0; wheels are on PyPI / conda forge.
(note: append to existing GPKG in memory / multiple layers are not yet supported)

**Comment by aetriusgx** [comment]
Hi, I'm coming across the same problem using the latest geopandas version. I had 0.14.2 installed through conda and upgraded to 1.0.1 which installed pyogrio, thinking this would be the solution. Upgrading geopandas to the latest version doesn't seem to have helped as I'm getting similar errors using fiona and pyogrio as the engine. I don't have an issue when I'm using an archive that contains an shp file, just when I directly use an shp file.

Markdown isn't cooperating so apologies that there's a bunch of uncollapsible text below.

## Code Sample
```python
file_picker = widgets.FileUpload(...)
display(file_picker)

def shp_to_geojson(obj: io.BytesIO, mode: str):
    path=""
    if mode == 'zip':
        ... # <-- unzips archive then reads file through file path
    if mode == 'shp':
        gdf = gpd.read_file(obj, engine='fiona') # <-- this produces the error

    gdf_4326 = gdf.to_crs(epsg=4326)

    geojson_dict = ast.literal_eval(gdf_4326.to_json())
    return geojson_dict

shp_to_geojson(io.BytesIO(file_picker.value[0].content), mode='shp')
```
## Expected output

### Stacktrace (fiona)
```txt
CPLE_OpenFailedError                      Traceback (most recent call last)
File fiona\\ogrext.pyx:136, in fiona.ogrext.gdal_open_vector()

File fiona\\_err.pyx:291, in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: '/vsimem/cb30eee9cf8c47b492d28e55207b47e9' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
Cell In[60], line 1
----> 1 shp_to_geojson(io.BytesIO(file_picker.value[0].content), mode='shp')

Cell In[59], line 31, in shp_to_geojson(obj, mode)
     29     gdf = gpd.read_file(shapefile_path)
     30 if mode == 'shp':
---> 31     gdf = gpd.read_file(obj, engine='fiona', driver='ESRI Shapefile')
     32 # 3. Convert to EPSG:4326
     33 gdf_4326 = gdf.to_crs(epsg=4326)

File ~\.conda\envs\python311\Lib\site-packages\geopandas\io\file.py:306, in _read_file(filename, bbox, mask, columns, rows, engine, **kwargs)
    303     else:
    304         path_or_bytes = filename
--> 306     return _read_file_fiona(
    307         path_or_bytes,
    308         from_bytes,
    309         bbox=bbox,
    310         mask=mask,
    311         columns=columns,
    312         rows=rows,
    313         **kwargs,
    314     )
    316 else:
    317     raise ValueError(f"unknown engine '{engine}'")

File ~\.conda\envs\python311\Lib\site-packages\geopandas\io\file.py:358, in _read_file_fiona(path_or_bytes, from_bytes, bbox, mask, columns, rows, where, **kwargs)
    355     reader = fiona.open
    357 with fiona_env():
--> 358     with reader(path_or_bytes, **kwargs) as features:
    359         crs = features.crs_wkt
    360         # attempt to get EPSG code

File ~\.conda\envs\python311\Lib\site-packages\fiona\collection.py:783, in BytesCollection.__init__(self, bytesbuf, **kwds)
    780 self.virtual_file = buffer_to_virtual_file(self.bytesbuf, ext=ext)
    782 # Instantiate the parent class.
--> 783 super().__init__(self.virtual_file, vsi=filetype, **kwds)
    784 self._closed = False

File ~\.conda\envs\python311\Lib\site-packages\fiona\collection.py:243, in Collection.__init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)
    241 if self.mode == "r":
    242     self.session = Session()
--> 243     self.session.start(self, **kwargs)
    244 elif self.mode in ("a", "w"):
    245     self.session = WritingSession()

File fiona\\ogrext.pyx:588, in fiona.ogrext.Session.start()

File fiona\\ogrext.pyx:143, in fiona.ogrext.gdal_open_vector()

DriverError: '/vsimem/cb30eee9cf8c47b492d28e55207b47e9' not recognized as a supported file format.
```

### Stacktrace (pyogrio)

```txt
DataSourceError                           Traceback (most recent call last)
Cell In[63], line 1
----> 1 shp_to_geojson(io.BytesIO(file_picker.value[0].content), mode='shp')

Cell In[62], line 31, in shp_to_geojson(obj, mode)
     29     gdf = gpd.read_file(shapefile_path)
     30 if mode == 'shp':
---> 31     gdf = gpd.read_file(obj)
     32 # 3. Convert to EPSG:4326
     33 gdf_4326 = gdf.to_crs(epsg=4326)

File ~\.conda\envs\python311\Lib\site-packages\geopandas\io\file.py:294, in _read_file(filename, bbox, mask, columns, rows, engine, **kwargs)
    291             from_bytes = True
    293 if engine == "pyogrio":
--> 294     return _read_file_pyogrio(
    295         filename, bbox=bbox, mask=mask, columns=columns, rows=rows, **kwargs
    296     )
    298 elif engine == "fiona":
    299     if pd.api.types.is_file_like(filename):

File ~\.conda\envs\python311\Lib\site-packages\geopandas\io\file.py:547, in _read_file_pyogrio(path_or_bytes, bbox, mask, rows, **kwargs)
    538     warnings.warn(
    539         "The 'include_fields' and 'ignore_fields' keywords are deprecated, and "
    540         "will be removed in a future release. You can use the 'columns' keyword "
   (...)
    543         stacklevel=3,
    544     )
    545     kwargs["columns"] = kwargs.pop("include_fields")
--> 547 return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)

File ~\.conda\envs\python311\Lib\site-packages\pyogrio\geopandas.py:265, in read_dataframe(path_or_buffer, layer, encoding, columns, read_geometry, force_2d, skip_features, max_features, where, bbox, mask, fids, sql, sql_dialect, fid_as_index, use_arrow, on_invalid, arrow_to_pandas_kwargs, **kwargs)
    260 if not use_arrow:
    261     # For arrow, datetimes are read as is.
    262     # For numpy IO, datetimes are read as string values to preserve timezone info
    263     # as numpy does not directly support timezones.
    264     kwargs["datetime_as_string"] = True
--> 265 result = read_func(
    266     path_or_buffer,
    267     layer=layer,
    268     encoding=encoding,
    269     columns=columns,
    270     read_geometry=read_geometry,
    271     force_2d=gdal_force_2d,
    272     skip_features=skip_features,
    273     max_features=max_features,
    274     where=where,
    275     bbox=bbox,
    276     mask=mask,
    277     fids=fids,
    278     sql=sql,
    279     sql_dialect=sql_dialect,
    280     return_fids=fid_as_index,
    281     **kwargs,
    282 )
    284 if use_arrow:
    285     meta, table = result

File ~\.conda\envs\python311\Lib\site-packages\pyogrio\raw.py:198, in read(path_or_buffer, layer, encoding, columns, read_geometry, force_2d, skip_features, max_features, where, bbox, mask, fids, sql, sql_dialect, return_fids, datetime_as_string, **kwargs)
     59 """Read OGR data source into numpy arrays.
     60 
     61 IMPORTANT: non-linear geometry types (e.g., MultiSurface) are converted
   (...)
    194 
    195 """
    196 dataset_kwargs = _preprocess_options_key_value(kwargs) if kwargs else {}
--> 198 return ogr_read(
    199     get_vsi_path_or_buffer(path_or_buffer),
    200     layer=layer,
    201     encoding=encoding,
    202     columns=columns,
    203     read_geometry=read_geometry,
    204     force_2d=force_2d,
    205     skip_features=skip_features,
    206     max_features=max_features or 0,
    207     where=where,
    208     bbox=bbox,
    209     mask=_mask_to_wkb(mask),
    210     fids=fids,
    211     sql=sql,
    212     sql_dialect=sql_dialect,
    213     return_fids=return_fids,
    214     dataset_kwargs=dataset_kwargs,
    215     datetime_as_string=datetime_as_string,
    216 )

File pyogrio\\_io.pyx:1240, in pyogrio._io.ogr_read()

File pyogrio\\_io.pyx:216, in pyogrio._io.ogr_open()

DataSourceError: '/vsimem/pyogrio_67ad6feb3f824feaa604ded769be8383' not recognized as being in a supported file format. It might help to specify the correct driver explicitly by prefixing the file path with '<DRIVER>:', e.g. 'CSV:path'.
```
### geopandas.show_versions() output
```txt
SYSTEM INFO
-----------
python     : 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\robin\.conda\envs\python311\python.exe
machine    : Windows-10-10.0.26100-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : None
GDAL       : 3.9.1
GDAL data dir: C:\Users\robin\.conda\envs\python311\Lib\site-packages\pyogrio\gdal_data\
PROJ       : 9.3.1
PROJ data dir: C:\Users\robin\.conda\envs\python311\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 1.0.1
numpy      : 1.26.4
pandas     : 2.2.2
pyproj     : 3.6.1
shapely    : 2.0.5
pyogrio    : 0.10.0
geoalchemy2: None
geopy      : 2.4.1
matplotlib : 3.8.4
mapclassify: 2.5.0
fiona      : 1.9.5
psycopg    : None
psycopg2   : None
pyarrow    : None
```

**Comment by brendan-ward** [comment]
@aetriusgx  if I'm reading your post correctly, the issue occurs when you have the bytes for an uncompressed shapefile stored within a BytesIO object?

That wouldn't be supported for either pyogrio or Fiona because a shapefile has multiple required files (at least *.shp, *.dbf, *.prj).  GDAL needs all of these available to process the shapefile, and there is no way to correctly represent a multi-file object within a set bytes in a BytesIO object.

Instead, the only way to read a shapefile from a BytesIO object is from within a zip file, since that defines the folder structure and file entities as part of the archive structure.

Formats that are composed of only a single file (e.g., GeoJSON, GPKG) should work properly via BytesIO.

Did I understand your issue correctly?
