### ISSUE TITLE
BUG: install 

### ISSUE THREAD

**Issue by amlos91** [geopandas/geopandas#3307]
Hey I have checked that this issue has not already been reported.

I tried 3 times my codes and I have no solution can someone help me ?
Installing requirements
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
Traceback (most recent call last):
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/modules/launch_utils.py", line 465, in start
    import webui
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/modules/initialize.py", line 26, in imports
    from modules import paths, timer, import_hook, errors  # noqa: F401
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/modules/paths.py", line 60, in <module>
    import sgm  # noqa: F401
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/models/__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/models/autoencoder.py", line 12, in <module>
    from ..modules.diffusionmodules.model import Decoder, Encoder
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/modules/__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/modules/encoders/modules.py", line 22, in <module>
    from ...modules.diffusionmodules.model import Encoder
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/modules/diffusionmodules/__init__.py", line 6, in <module>
    from .sampling import BaseDiffusionSampler
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/modules/diffusionmodules/sampling.py", line 12, in <module>
    from ...modules.diffusionmodules.sampling_utils import (
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/repositories/generative-models/sgm/modules/diffusionmodules/sampling_utils.py", line 2, in <module>
    from scipy import integrate
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/integrate/__init__.py", line 94, in <module>
    from ._quadrature import *
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/integrate/_quadrature.py", line 9, in <module>
    from scipy.special import roots_legendre
  File "/Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/special/__init__.py", line 777, in <module>
    from . import _ufuncs
ImportError: dlopen(/Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/special/_ufuncs.cpython-310-darwin.so, 2): Symbol not found: _cephes_Gamma
  Referenced from: /Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/special/_ufuncs.cpython-310-darwin.so
  Expected in: flat namespace
 in /Users/borisvian/stablediffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/scipy/special/_ufuncs.cpython-310-darwin.so

**Comment by martinfleis** [comment]
I am sorry, how does this relate to `geopandas`?
