### ISSUE TITLE
BUG: S3 with request payer enabled does not work

### ISSUE THREAD

**Issue by frediana** [geopandas/geopandas#3310]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
from geopandas import read_file

res = read_file(
    "s3://xxxxx/xxxx.shp", # an object that reside on a bucket xxxx with "request-payer mode enabled"
    kwargs={"requester_pays": True},
)

print(res)
```

#### Problem description

I want to read a file using geopandas, this file reside on an AWS S3 bucket that has enabled the mode "requester-payer".

The snippet provided, does not work, I observe the following error:

```
Traceback (most recent call last):
  File "fiona/ogrext.pyx", line 136, in fiona.ogrext.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_AWSAccessDeniedError: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    res = read_file(
          ^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/geopandas/io/file.py", line 289, in _read_file
    return _read_file_fiona(
           ^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/geopandas/io/file.py", line 315, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/fiona/__init__.py", line 292, in open
    colxn = Collection(
            ^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/fiona/collection.py", line 243, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 588, in fiona.ogrext.Session.start
  File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
fiona.errors.DriverError: Access Denied
```

Since I have the hand on the source bucket, by disabling the request-payer mode, everything works fine with the exact same line of code.

**Comment by m-richards** [comment]
Thanks @frediana for the report, I expect this might be a little hard to test. Are you able to try using fiona directly (https://fiona.readthedocs.io/en/stable/manual.html#cloud-storage-credentials). As I understand it doesn't look like this is supported there, but it would be good to confirm that this isn't an issue with feeding through arguments
