### ISSUE TITLE
BUG: `numpy@^1.25` raises `DeprecationWarning: Conversion of an array with ndim > 0 to a scalar` when running `.to_crs()` on a `GeoDataFrame` with 1 row

### ISSUE THREAD

**Issue by romaingd-spi** [geopandas/geopandas#3430]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

Hi, and thanks for the work on `geopandas`!
I'm not sure whether this is a `geopandas` or `pyproj` issue.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely import Point

gdf = gpd.GeoDataFrame(geometry=[Point(1., 2.)], crs="EPSG:4326")
gdf.to_crs(crs="epsg:32603")
```

#### Problem description

The code sample, when run with appropriate flags to spot deprecation warnings (e.g. `python -W error:Conversion:DeprecationWarning`), raises the following `DeprecationWarning`:

```python-traceback
Traceback (most recent call last):
  File "/home/user/spinergie/spindata/tmp.py", line 5, in <module>
    gdf.to_crs(crs="epsg:32603")
  File "/home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1410, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/geopandas/geoseries.py", line 1175, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "/home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/geopandas/array.py", line 872, in to_crs
    new_data = vectorized.transform(self._data, transformer.transform)
  File "/home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/geopandas/_vectorized.py", line 1289, in transform
    new_coords_z = func(coords[:, 0], coords[:, 1])
  File "/home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/pyproj/transformer.py", line 820, in transform
    return self._transformer._transform_point(
  File "pyproj/_transformer.pyx", line 762, in pyproj._transformer._Transformer._transform_point
DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
```

This warning is only raised when `geometry` contains a single element - using `geometry=[Point(1.0, 2.0), Point(1.0, 3.0)]` does not raise any warning.

This is an problem for the present for setups that turn all warnings to errors to keep ahead on maintenance, and expectedly (though I couldn't test it) for the future when the `numpy` deprecation expires and the code no longer works. It's also not intuitive that the behavior is different when `geometry` contains multiple elements.

#### Expected Output

No warnings raised (and most importantly, no issue when the `numpy` deprecation expires, although I couldn't test it)

#### Output of ``geopandas.show_versions()``

<details>

```
SYSTEM INFO
-----------
python     : 3.9.20 (main, Sep  7 2024, 18:35:25)  [GCC 11.4.0]
executable : /home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/bin/python
machine    : Linux-6.8.0-45-generic-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.4
GEOS lib   : None
GDAL       : 3.9.2
GDAL data dir: /home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 9.3.0
PROJ data dir: /home/user/.cache/pypoetry/virtualenvs/spindata-OX3-oLdu-py3.9/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.4
numpy      : 1.26.4
pandas     : 1.4.4
pyproj     : 3.6.1
shapely    : 2.0.6
fiona      : 1.10.0
geoalchemy2: None
geopy      : 2.4.1
matplotlib : 3.9.0
mapclassify: None
pygeos     : None
pyogrio    : 0.9.0
psycopg2   : 2.9.9 (dt dec pq3 ext lo64)
pyarrow    : 15.0.2
rtree      : None
```

</details>

**Comment by m-richards** [comment]
@romaingd-spi this originates upstream in pyproj - which is not supressing the warning internally due to the performance hit - see https://github.com/pyproj4/pyproj/issues/1307.

Given this, there's not really a whole lot GeoPandas can do - I suppose we could special case surpress the len one case, but I'd rather not introduce special casing code for this.

**Comment by romaingd-spi** [comment]
Thanks @m-richards for the quick answer and the link to the source issue! I should have checked `pyproj` issues first, my bad. I'm fine with ignoring the warning knowing that the problem is identified.
