### ISSUE TITLE
BUG: GeoSeries init function can't handle data type like `Series(GeoSeries)` in geopandas 1.x

### ISSUE THREAD

**Issue by Zeroto521** [geopandas/geopandas#3452]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import geopandas as gpd
>>> import pandas as pd
>>> s = pd.Series(
...     gpd.GeoSeries.from_wkt(
...         [
...             "POINT (1 1)",
...             "POINT (2 2)",
...             "POINT (3 3)",
...         ],
...         name="wkt",
...         crs=4326,
...     ).geometry
... )
>>> s
0    POINT (1 1)
1    POINT (2 2)
2    POINT (3 3)
Name: wkt, dtype: geometry
>>> type(s)
<class 'pandas.core.series.Series'>
>>> gpd.GeoSeries(s, crs=4326)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\Zero\AppData\Local\mambaforge\envs\work\Lib\site-packages\geopandas\geoseries.py", line 168, in __init__
    if not data.crs == crs:
           ^^^^^^^^
  File "D:\Users\Zero\AppData\Local\mambaforge\envs\work\Lib\site-packages\pandas\core\generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'crs'
```

#### Problem description

The `s` is a `Series(GeoSeries)` data, so the CRS should come from its inner data.
`data.crs` variable shoud change to`data_crs`.

https://github.com/geopandas/geopandas/blob/9e3f6dbadfcbe103cea46aef64507c49fa3b9020/geopandas/geoseries.py#L162-L173

#### Output of ``geopandas.show_versions()``

<details>

```
SYSTEM INFO
-----------
python     : 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:17:14) [MSC v.1941 64 bit (AMD64)]
executable : D:\Users\Zero\AppData\Local\mambaforge\envs\work\python.exe
machine    : Windows-10-10.0.19045-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.13.0
GEOS lib   : None
GDAL       : 3.9.3
GDAL data dir: D:\Users\Zero\AppData\Local\mambaforge\envs\work\Library\share\gdal\
PROJ       : 9.5.0
PROJ data dir: D:\Users\Zero\AppData\Local\mambaforge\envs\work\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 1.0.1
numpy      : 2.1.2
pandas     : 2.2.3
pyproj     : 3.7.0
shapely    : 2.0.6
pyogrio    : 0.10.0
geoalchemy2: None
geopy      : None
matplotlib : 3.9.2
mapclassify: 2.8.1
fiona      : 1.10.1
psycopg    : None
psycopg2   : None
pyarrow    : None
```

</details>

**Comment by m-richards** [comment]
Thanks for the report, in the meantime this was already fixed in https://github.com/geopandas/geopandas/pull/3383 - just waiting on a 1.0.2 / 1.1. release
