### ISSUE TITLE
centos Could not find lib geos_c

### ISSUE THREAD

**Issue by geoHeil** [geopandas/geopandas#395]
When trying to use geopandas on a minimal centos 7.3 install with python 2.7.13 I get an error like 
`Could not find lib geos_c`. Trying to fix it via `sudo yum install libgeos-dev` fails with package not found.

Is there a repository I am missing?

**Comment by jorisvandenbossche** [comment]
You will need to give a bit more information. How did you try to install geopandas? Using `pip`, from source or with conda?

In any case, I personally recommend to use conda to install geopandas. Especially for its difficult dependencies (gdal, geos, proj), this makes it a lot easier.

**Comment by geoHeil** [comment]
@jorisvandenbossche  I tried it with conda and pip. Both failed. The error message of conda was very cryptic but a c file was missing

Then I tried pip which results in the more understandable error message. So far I did not succeed in installing libgeos-dev on centos.

**Comment by jorisvandenbossche** [comment]
Again, if you want help, you will need to give more information. Eg show exactly what you tried in conda and the error messages you got.

**Comment by geoHeil** [comment]
@jorisvandenbossche 

here are the steps one by one after using a fresh centos 7.3 minimal iso
```
wget https://repo.continuum.io/archive/Anaconda2-4.3.0-Linux-x86_64.sh
sudo yum -y install bzip2
hmod +x Anaconda2-4.3.0-Linux-x86_64.sh
./Anaconda2-4.3.0-Linux-x86_64.sh

#accept all, use defaults, do not add to path
export PATH="$HOME/anaconda/bin:$PATH"

conda install -c conda-forge geopandas

# then start a python interpreter
# for me the version is 2.7.13
python

# and load geopandas
import geopandas
```

which will produce the following error:
```
raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```

**Comment by geoHeil** [comment]
@jorisvandenbossche when trying now to install it via pip in an empty environment:
```
conda conda create -n py275 python=2.7.5
source activate py275
pip install geopandas

# when I now try to load geopandas
import geopandas
```

the error is as reported at the beginning.
```
Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/geopandas/geoseries.py", line 10, in <module>
    from shapely.geometry import box, shape, Polygon, Point
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/shapely/geos.py", line 66, in <module>
    _lgeos = load_dll('geos_c', fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
  File "/home/vagrant/anaconda2/envs/py275/lib/python2.7/site-packages/shapely/geos.py", line 61, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
```

**Comment by jorisvandenbossche** [comment]
That the pip install fails with that error is to be expected I think, as geos is not automatically installed.

The conda error is a problem with the fiona install. Can you report this issue over here: https://github.com/conda-forge/fiona-feedstock/issues ? 
Best also to provide the output of the ``conda install`` and the output ``conda list``

**Comment by jorisvandenbossche** [comment]
One thing you could also try to do is: ``conda install icu=56.1`` and see if this fixes the problem

**Comment by geoHeil** [comment]
Created an Issue https://github.com/conda-forge/fiona-feedstock/issues/34

**Comment by geoHeil** [comment]
That wont work: PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - icu 56.1*

**Comment by geoHeil** [comment]
@jorisvandenbossche 
> That the pip install fails with that error is to be expected I think, as geos is not automatically installed.
That is what I mentioned in the early beginning. But so far it was not possible for me to install geos library on centos. `sudo yum install libgeos-dev` is telling me that the software is not found. Is there a repository I am missing?

**Comment by jorisvandenbossche** [comment]
>  Is there a repository I am missing?

Sorry, not familiar with centos.

> That wont work: PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:

``conda install -c conda-forge icu=58.1`` should work (https://anaconda.org/conda-forge/icu)

**Comment by geoHeil** [comment]
@jorisvandenbossche unfortunately, that will not work as well:

```
conda install -c conda-forge icu=58.1
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/vagrant/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    icu-58.1                   |                0        22.7 MB  conda-forge
    anaconda-custom            |           py27_0           3 KB
    qt-4.8.7                   |                3        34.1 MB
    pyqt-4.11.4                |           py27_2         3.5 MB  conda-forge
    anaconda-navigator-1.2.3   |           py27_0         3.0 MB
    matplotlib-1.5.1           |      np111py27_0         8.2 MB
    qtconsole-4.2.1            |           py27_1         138 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        71.7 MB

The following packages will be UPDATED:

    anaconda:           4.3.0-np111py27_0 --> custom-py27_0
    icu:                54.1-0            --> 58.1-0            conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    pyqt:               5.6.0-py27_2      --> 4.11.4-py27_2     conda-forge
    qtconsole:          4.2.1-py27_1      --> 4.2.1-py27_1      conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.4.3-py27_0      --> 1.2.3-py27_0
    matplotlib:         2.0.0-np111py27_0 --> 1.5.1-np111py27_0
    qt:                 5.6.2-3           --> 4.8.7-3

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
icu-58.1-0.tar 100% |###########################################################################################################################################################| Time: 0:00:21   1.12 MB/s
anaconda-custo 100% |###########################################################################################################################################################| Time: 0:00:00   4.51 MB/s
qt-4.8.7-3.tar 100% |###########################################################################################################################################################| Time: 0:00:05   6.04 MB/s
pyqt-4.11.4-py 100% |###########################################################################################################################################################| Time: 0:00:03   1.11 MB/s
anaconda-navig 100% |###########################################################################################################################################################| Time: 0:00:05 598.28 kB/s
matplotlib-1.5 100% |###########################################################################################################################################################| Time: 0:00:01   7.39 MB/s
qtconsole-4.2. 100% |###########################################################################################################################################################| Time: 0:00:01 120.48 kB/s
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################################################################################################################################| 100%
(root) [vagrant@mn01 ~]$ python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import geopandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/vagrant/anaconda2/lib/python2.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```

**Comment by jorisvandenbossche** [comment]
As @ocefpaf says on the fiona issue, it best to also have qt and the other packages from conda-forge. 

Going to close it here, as discussion is best done further in https://github.com/conda-forge/fiona-feedstock/issues/34 I think
