### ISSUE TITLE
Installation problem with geopandas

### ISSUE THREAD

**Issue by msaharia** [geopandas/geopandas#620]
I am running into this error when I do `import geopandas`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /glade/u/apps/ch/os/usr/lib64/libk5crypto.so.3: symbol k5_buf_data, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
```
Also,

```
@ $ cat ~/.condarc
channel_priority: true
channels:
  - conda-forge
  - default
```

**Comment by jorisvandenbossche** [comment]
Can you show the full output of the "conda install geopandas" command you did?

**Comment by jorisvandenbossche** [comment]
Let's continue discussion in https://github.com/conda-forge/geopandas-feedstock/issues/28, closing here
