### ISSUE TITLE
Issue using Join on layers

### ISSUE THREAD

**Issue by GISConsortium** [geopandas/geopandas#625]
My Script:

import geopandas as gpd
fp=r"C:\Shared\Test_Data\geopandastest\Vaestotietoruudukko_2015\Vaestotietoruudukko_2015.shp"
pop = gpd.read_file(fp)
addr_fp =r'C:\Shared\Test_Data\geopandastest\address\addresses_epsg3879.shp'
addresses = gpd.read_file(addr_fp)
join = gpd.sjoin(addresses, pop, how="inner", op="within")

I am getting this error:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "C:\Python27\lib\site-packages\rtree\index.py", line 717, in py_next_item
    p_dimension[0] = dimension
ValueError: NULL pointer access
Traceback (most recent call last):
  Python Shell, prompt 25, line 1
  File "C:\Python27\Lib\site-packages\geopandas\tools\sjoin.py", line 69, in sjoin
    tree_idx = rtree.index.Index(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\rtree\core.py", line 28, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.

**Comment by jorisvandenbossche** [comment]
@GISConsortium Can you provide a reproducible example? Eg make a dummy GeoDataFrame with code that reproduces the problem (or if that is not possible, a downloadable shapefile).

**Comment by GISConsortium** [comment]
I gave a link from where you can download the data I have used. 
You can download them from here
-- [dataset-1](https://github.com/Python-GIS/latest/blob/master/data/addresses_epsg3879.shp) (download all additional file too)
https://github.com/Python-GIS/latest/blob/master/data/addresses_epsg3879.shp
 --[dataset-2 ](https://www.hsy.fi/sites/AvoinData/AvoinData/SYT/Tietoyhteistyoyksikko/Shape%20(Esri)/V%C3%A4est%C3%B6tietoruudukko/Vaestotietoruudukko_2015.zip)

**Comment by GISConsortium** [comment]
joinLyr_ByLoc(r"C:\Shared\Test_Data\Point_Lyr.shp",r"C:\Shared\Test_Data\Polygon_Lyr.shp",joinOperat="within")

Simplified error:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "C:\Python27\lib\site-packages\rtree\index.py", line 717, in py_next_item
    p_dimension[0] = dimension
ValueError: NULL pointer access
<class 'rtree.core.RTreeError'>

**Comment by bobhaffner** [comment]
@GISConsortium the links you provided are missing the supporting files(eg .shx) for the addresses_epsg3879.shp file

**Comment by samrogers226** [comment]
@GISConsortium did you ever find a fix for this?
