### ISSUE TITLE
Cannot import geopandas in PyInstaller executable

### ISSUE THREAD

**Issue by joskaaaa** [geopandas/geopandas#792]
Exporting the simplest python script as an executable with PyInstaller returns an error. While the script runs fine uncompiled in the virtual environment, it fails to run once compiled.

Source code:

`import geopandas as gpd`

Will return the following console output once compiled:

`Traceback (most recent call last):
  File "application.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\documents\projecttwo\publish\harv_venv1\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\documents\projecttwo\publish\harv_venv1\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\datasets\__init__.py", line 7, in <module>
StopIteration`

This is true for versions 0.4.0, 0.3.0, and 0.2.1 of Geopandas with PyInstaller version 3.3.1 on Windows.

**Comment by jdmcbr** [comment]
I think [your stackoverflow post](https://stackoverflow.com/questions/51662773/cannot-import-geopandas-with-pyinstaller-executable-despite-running-fine-in-th) is a better venue for this question. I have no experience with pyinstaller, but I strongly suspect this is related to details of the compilation (which I suppose would be a little tricky with the GDAL/GEOS dependencies, though the error above doesn't hint at any of that). I hope you find someone who knows how to get it working!

**Comment by joskaaaa** [comment]
Thanks!

**Comment by awa5114** [comment]
I am also facing this problem @joskaaa were you able to find a solution?

**Comment by joskaaaa** [comment]
@awa5114 , see [my StackOverflow post](https://stackoverflow.com/questions/51662773/cannot-import-geopandas-with-pyinstaller-executable-despite-running-fine-in-th) for a possible solution. 

For this particular project I just used Cx_freeze instead of Pyinstaller.
