### ISSUE TITLE
`conda` installation has issues with `fiona`

### ISSUE THREAD

**Issue by austinorr** [geopandas/geopandas#806]
This appears to be a recurring problem of keeping `fiona` and `geopandas` in sync but i haven't found a work around this time. 

on windows amdx64 clean install with conda:
```
>conda create -n exe -c conda-forge python=3.6 geopandas
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Python35\envs\exe

  added / updated specs:
    - geopandas
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fiona-1.7.13               |   py36h2fc6367_3         675 KB  conda-forge
    certifi-2018.8.13          |           py36_0         138 KB  conda-forge
    gdal-2.2.4                 |   py36h2fc6367_1         830 KB  conda-forge
    matplotlib-2.2.3           |   py36h31860fd_0         6.5 MB  conda-forge
    tornado-5.1                |   py36hfa6e2cd_1         668 KB  conda-forge
    pysal-1.14.4.post2         |           py36_0        15.1 MB  conda-forge
    kiwisolver-1.0.1           |   py36he980bc4_2          59 KB  conda-forge
    pandas-0.23.4              |   py36h830ac7b_0         8.7 MB  conda-forge
    sqlalchemy-1.2.11          |   py36hfa6e2cd_0         1.6 MB  conda-forge
    mkl_fft-1.0.6              |           py36_0         121 KB  conda-forge
    psycopg2-2.7.5             |   py36h74b6da3_1         295 KB  conda-forge
    mkl_random-1.0.1           |           py36_0         267 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        34.8 MB

The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-hfa6e2cd_2      conda-forge
    ca-certificates: 2018.8.13-ha4d7672_0  conda-forge
    certifi:         2018.8.13-py36_0      conda-forge
    click:           6.7-py_1              conda-forge
    click-plugins:   1.0.3-py_1            conda-forge
    cligj:           0.4.0-py36_0          conda-forge
    curl:            7.61.0-h7602738_0
    cycler:          0.10.0-py_1           conda-forge
    descartes:       1.1.0-py_2            conda-forge
    expat:           2.2.5-he025d50_1      conda-forge
    fiona:           1.7.13-py36h2fc6367_3 conda-forge
    freetype:        2.9.1-he8b6a0d_1      conda-forge
    freexl:          1.0.5-hd288d7e_1      conda-forge
    gdal:            2.2.4-py36h2fc6367_1  conda-forge
    geopandas:       0.4.0-py_1            conda-forge
    geos:            3.6.2-he025d50_2      conda-forge
    geotiff:         1.4.2-h2080a26_2      conda-forge
    hdf4:            4.2.13-h712560f_2
    hdf5:            1.10.2-hbc3b0e7_1     conda-forge
    icc_rt:          2017.0.4-h97af966_0
    icu:             58.2-ha66f8fd_1
    intel-openmp:    2018.0.3-0
    jpeg:            9c-hfa6e2cd_0         conda-forge
    kealib:          1.4.9-h4380d0d_2      conda-forge
    kiwisolver:      1.0.1-py36he980bc4_2  conda-forge
    libcurl:         7.61.0-h7602738_0
    libgdal:         2.2.4-hf00ed0c_6      conda-forge
    libiconv:        1.15-hfa6e2cd_2       conda-forge
    libnetcdf:       4.6.1-ha2173a7_7      conda-forge
    libpng:          1.6.35-h7602738_0     conda-forge
    libpq:           9.6.6-h14f23c8_0
    libspatialindex: 1.8.5-he025d50_2      conda-forge
    libspatialite:   4.3.0a-h582a839_21    conda-forge
    libssh2:         1.8.0-hc4dcbb0_2      conda-forge
    libtiff:         4.0.9-hf1753bf_1      conda-forge
    libxml2:         2.9.8-h9ce36c8_3      conda-forge
    matplotlib:      2.2.3-py36h31860fd_0  conda-forge
    mkl:             2018.0.3-1
    mkl_fft:         1.0.6-py36_0          conda-forge
    mkl_random:      1.0.1-py36_0          conda-forge
    munch:           2.3.2-py_0            conda-forge
    numpy:           1.14.2-py36h5c71026_1
    openjpeg:        2.3.0-h25a6d84_3      conda-forge
    openssl:         1.0.2o-hfa6e2cd_1     conda-forge
    pandas:          0.23.4-py36h830ac7b_0 conda-forge
    pip:             18.0-py36_1           conda-forge
    proj4:           4.9.3-hcf24537_7
    psycopg2:        2.7.5-py36h74b6da3_1  conda-forge
    pyparsing:       2.2.0-py_1            conda-forge
    pyproj:          1.9.5.1-py36_0        conda-forge
    pyqt:            5.6.0-py36h764d66f_6  conda-forge
    pysal:           1.14.4.post2-py36_0   conda-forge
    python:          3.6.6-he025d50_0      conda-forge
    python-dateutil: 2.7.3-py_0            conda-forge
    pytz:            2018.5-py_0           conda-forge
    qt:              5.6.2-h2639256_8      conda-forge
    rtree:           0.8.3-py36_0          conda-forge
    scipy:           1.1.0-py36h672f292_0
    setuptools:      40.0.0-py36_1         conda-forge
    shapely:         1.6.4-py36hc90234e_1  conda-forge
    sip:             4.18-py36_1           conda-forge
    six:             1.11.0-py36_1         conda-forge
    sqlalchemy:      1.2.11-py36hfa6e2cd_0 conda-forge
    sqlite:          3.24.0-hb652765_0     conda-forge
    tornado:         5.1-py36hfa6e2cd_1    conda-forge
    vc:              14.1-h0510ff6_3
    vs2015_runtime:  15.5.2-3
    wheel:           0.31.1-py36_1         conda-forge
    wincertstore:    0.2-py36_2            conda-forge
    xerces-c:        3.2.0-h44c76bb_2
    xz:              5.2.4-h2fa13f4_1      conda-forge
    zlib:            1.2.11-h2fa13f4_3     conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
fiona-1.7.13         | 675 KB    | ########################################################### | 100%
certifi-2018.8.13    | 138 KB    | ########################################################### | 100%
gdal-2.2.4           | 830 KB    | ########################################################### | 100%
matplotlib-2.2.3     | 6.5 MB    | ########################################################### | 100%
tornado-5.1          | 668 KB    | ########################################################### | 100%
pysal-1.14.4.post2   | 15.1 MB   | ########################################################### | 100%
kiwisolver-1.0.1     | 59 KB     | ########################################################### | 100%
pandas-0.23.4        | 8.7 MB    | ########################################################### | 100%
sqlalchemy-1.2.11    | 1.6 MB    | ########################################################### | 100%
mkl_fft-1.0.6        | 121 KB    | ########################################################### | 100%
psycopg2-2.7.5       | 295 KB    | ########################################################### | 100%
mkl_random-1.0.1     | 267 KB    | ########################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
attempt to use:
```
>activate exe
(exe)>python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import geopandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Python35\envs\exe\lib\site-packages\geopandas\__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "C:\Users\Python35\envs\exe\lib\site-packages\geopandas\io\file.py", line 3, in <module>
    import fiona
  File "C:\Users\Python35\envs\exe\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "C:\Users\Python35\envs\exe\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.
```

Installing from `conda-forge` was recently the most reliable way to get all the dependencies working well together. Is there another recommended way now e.g., `pip` or `conda`s default channel?

**Comment by austinorr** [comment]
Thanks for this reply, I didn’t realize how this change in `conda` would effect my project. Closing.
