### ISSUE TITLE
Inconsistent behaviour when calculating sizeof GeoDataFrame and GeoSeries in DASK

### ISSUE THREAD

**Issue by avnovikov** [geopandas/geopandas#819]
This is a companion issue for the DASK  issue [#3976](https://github.com/dask/dask/issues/3976).
Some toy example:
```
import pandas as pd
import numpy as np
import geopandas as gpd

import dask.dataframe as dd
from distributed import Client
from shapely.geometry import Point

client = Client('127.0.0.1:8786', processes=True)
length = 10000
data_pos = (np.random.rand(length,2)-0.5)*90
z = list(map(Point, data_pos))

df = gpd.GeoDataFrame({'116': list(np.ones((length, 1))), 'geometry': z}, crs={'init': 'epsg:4326'})
buffer = df.geometry.buffer(0.05)
df['buffer'] = buffer

sharbours = client.scatter(buffer)
sharbours = client.scatter(df)
```
among the various error messages there is on that can be perceived as  the possible  root cause. It is for the `sharbours = client.scatter(buffer)` that doesn't generate any **errors** but only warnings.

```
AttributeError: 'GeometryArray' object has no attribute 'nbytes'
distributed.sizeof - WARNING - Sizeof calculation failed.  Defaulting to 1MB
Traceback (most recent call last):
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/sizeof.py", line 16, in safe_sizeof
    return sizeof(obj)
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/dask/utils.py", line 415, in __call__
    return meth(arg)
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/dask/sizeof.py", line 63, in sizeof_pandas_series
    p = int(s.memory_usage(index=True))
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/pandas/core/series.py", line 3503, in memory_usage
    v = super(Series, self).memory_usage(deep=deep)
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/pandas/core/base.py", line 1143, in memory_usage
    v = self.values.nbytes
```

DASK is failing in p = int(s.memory_usage(index=True)) as can be found in the error log, but

```
type(anchorage_buffer)
Out[55]:
geopandas.geoseries.GeoSeries
In [57]:
anchorage_buffer.memory_usage(index=True)
I am densified (external_values, 20353 elements)
I am densified (external_values, 20353 elements)
Out[57]:
325648
```

**Comment by jorisvandenbossche** [comment]
@avnovikov thanks for the report! 
So basically the issue is that `GeometryArray` does not have a `nbytes` attributes, which we need to add anyhow when moving towards full ExtensionArray support. 

But the question is still what to actually report here. Currently what you get with `memory_usage` is the memory usage in the python process (so the pointers to the C objects), and not the memory usage of the actual GEOS objects. And I am not directly sure if they have any API to get memory usage.
