### ISSUE TITLE
gdp 0.4.1 still cannot recognize "scheme" when plotting

### ISSUE THREAD

**Issue by MorningMoment** [geopandas/geopandas#940]
I am using Python 3.6.5 and had updated to GeoPandas 0.4.1, pysal 2.0.0.
The plotting code is 
`departments_map.plot(column_n, ax=ax, cmap=plt.cm.plasma, scheme='fisher_jenks', k=10, legend=True)`
 But still the "scheme" problem is not solved after I update the GeoPandas.

```
fig, ax = plt.subplots(1, figsize=(15,14))
ax.set_title('Salary by Departments', size=32, x = 0.25, y=0.90)
fig.patch.set_facecolor((202/255, 204/255, 206/255))
column_n = 'SNHMF14'
departments_map.plot(column_n, ax=ax, cmap=plt.cm.plasma, scheme='fisher_jenks', k=10, legend=True)
leg = ax.get_legend()
ax.set_axis_off()
leg.set_bbox_to_anchor((0., 0., 0.2, 0.45))
leg.set_title("Mean net salary")
Traceback (most recent call last):

  File "<ipython-input-5-4994ea9669b6>", line 5, in <module>
    departments_map.plot(column_n, ax=ax, cmap=plt.cm.plasma, scheme='fisher_jenks', k=10, legend=True)

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 2941, in __call__
    sort_columns=sort_columns, **kwds)

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 1977, in plot_frame
    **kwds)

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 1804, in _plot
    plot_obj.generate()

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 260, in generate
    self._make_plot()

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 985, in _make_plot
    **kwds)

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 1001, in _plot
    lines = MPLPlot._plot(ax, x, y_values, style=style, **kwds)

  File "F:\Python\lib\site-packages\pandas\plotting\_core.py", line 615, in _plot
    return ax.plot(*args, **kwds)

  File "F:\Python\lib\site-packages\matplotlib\__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)

  File "F:\Python\lib\site-packages\matplotlib\axes\_axes.py", line 1527, in plot
    for line in self._get_lines(*args, **kwargs):

  File "F:\Python\lib\site-packages\matplotlib\axes\_base.py", line 406, in _grab_next_args
    for seg in self._plot_args(this, kwargs):

  File "F:\Python\lib\site-packages\matplotlib\axes\_base.py", line 396, in _plot_args
    seg = func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)

  File "F:\Python\lib\site-packages\matplotlib\axes\_base.py", line 300, in _makeline
    seg = mlines.Line2D(x, y, **kw)

  File "F:\Python\lib\site-packages\matplotlib\lines.py", line 421, in __init__
    self.update(kwargs)

  File "F:\Python\lib\site-packages\matplotlib\artist.py", line 888, in update
    for k, v in props.items()]

  File "F:\Python\lib\site-packages\matplotlib\artist.py", line 888, in <listcomp>
    for k, v in props.items()]

  File "F:\Python\lib\site-packages\matplotlib\artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)

AttributeError: Unknown property scheme
```

**Comment by jorisvandenbossche** [comment]
From the traceback, it seems that `departments_map` is a DataFrame, and not a GeoDataFrame.

**Comment by MorningMoment** [comment]
@jorisvandenbossche My apology. Yes I missed that it should be a GeoDataFrame. Problem Solved.
Thanks!!
