### ISSUE TITLE
v0.4.1 import error with CentOS

### ISSUE THREAD

**Issue by jGaboardi** [geopandas/geopandas#941]
* unable to import `geopandas` v0.4.1 (`conda-forge` channel) in clean `miniconda` environment on CentOS
* Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
* seems to be related to the ongoing `fiona` compatibility issues
* complete workflow / traceback below

```
(base) [USER@hpc-login-25 ~]$ conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'http://conda.anaconda.org/gurobi'
--add channels 'http://conda.anaconda.org/conda-forge'   # highest priority
(base) [USER@hpc-login-25 ~]$ conda create -n geopandas_env python=3.6
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.7

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /gpfs/home/USER/miniconda3/envs/geopandas_env

  added / updated specs: 
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.11.29-ha4d7672_0 conda-forge
    certifi:         2018.11.29-py36_1000  conda-forge
    libffi:          3.2.1-hf484d3e_1005   conda-forge
    libgcc-ng:       7.3.0-hdf63c60_0      conda-forge
    libstdcxx-ng:    7.3.0-hdf63c60_0      conda-forge
    ncurses:         6.1-hf484d3e_1002     conda-forge
    openssl:         1.1.1b-h14c3975_1     conda-forge
    pip:             19.0.3-py36_0         conda-forge
    python:          3.6.7-h381d211_1004   conda-forge
    readline:        7.0-hf8c457e_1001     conda-forge
    setuptools:      40.8.0-py36_0         conda-forge
    sqlite:          3.26.0-h67949de_1001  conda-forge
    tk:              8.6.9-h84994c4_1000   conda-forge
    wheel:           0.33.1-py36_0         conda-forge
    xz:              5.2.4-h14c3975_1001   conda-forge
    zlib:            1.2.11-h14c3975_1004  conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate geopandas_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [USER@hpc-login-25 ~]$ conda activate geopandas_env
(geopandas_env) [USER@hpc-login-25 ~]$ conda install -c conda-forge geopandas
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.7

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /gpfs/home/USER/miniconda3/envs/geopandas_env

  added / updated specs: 
    - geopandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fontconfig-2.13.1          |    h2176d3f_1000         334 KB  conda-forge
    cairo-1.14.12              |    h80bd089_1005         1.4 MB  conda-forge
    matplotlib-3.0.3           |           py36_0           6 KB  conda-forge
    libspatialite-4.3.0a       |    h9968ff2_1023         3.1 MB  conda-forge
    pthread-stubs-0.4          |    h14c3975_1001           5 KB  conda-forge
    libgdal-2.2.4              |       he036fc0_8        15.7 MB  conda-forge
    numpy-1.16.2               |   py36h7e9f1db_0          49 KB
    xorg-libsm-1.2.3           |    h4937e3b_1000          25 KB  conda-forge
    blas-1.0                   |              mkl           6 KB
    ------------------------------------------------------------
                                           Total:        20.7 MB

The following NEW packages will be INSTALLED:

    blas:             1.0-mkl                               
    boost-cpp:        1.68.0-h11c811c_1000       conda-forge
    bzip2:            1.0.6-h14c3975_1002        conda-forge
    cairo:            1.14.12-h80bd089_1005      conda-forge
    click:            7.0-py_0                   conda-forge
    click-plugins:    1.0.4-py_0                 conda-forge
    cligj:            0.5.0-py_0                 conda-forge
    curl:             7.64.0-h646f8bb_2          conda-forge
    cycler:           0.10.0-py_1                conda-forge
    dbus:             1.13.2-h714fa37_1                     
    descartes:        1.1.0-py_2                 conda-forge
    expat:            2.2.5-hf484d3e_1002        conda-forge
    fiona:            1.7.13-py36hb00a9d7_4      conda-forge
    fontconfig:       2.13.1-h2176d3f_1000       conda-forge
    freetype:         2.9.1-h94bbf69_1005        conda-forge
    freexl:           1.0.5-h14c3975_1002        conda-forge
    gdal:             2.2.4-py36hb00a9d7_1       conda-forge
    geopandas:        0.4.1-py_0                 conda-forge
    geos:             3.6.2-hfc679d8_4           conda-forge
    geotiff:          1.4.2-hfe6da40_1005        conda-forge
    gettext:          0.19.8.1-h9745a5d_1001     conda-forge
    giflib:           5.1.4-h14c3975_1001        conda-forge
    glib:             2.56.2-had28632_1001       conda-forge
    gst-plugins-base: 1.14.0-hbbd80ab_1                     
    gstreamer:        1.14.0-hb453b48_1                     
    hdf4:             4.2.13-h9a582f1_1002       conda-forge
    hdf5:             1.10.2-hc401514_3          conda-forge
    icu:              58.2-hf484d3e_1000         conda-forge
    intel-openmp:     2019.1-144                            
    jpeg:             9c-h14c3975_1001           conda-forge
    json-c:           0.12.1-h470a237_1          conda-forge
    kealib:           1.4.9-h0bee7d0_2           conda-forge
    kiwisolver:       1.0.1-py36h6bb024c_1002    conda-forge
    krb5:             1.16.3-h05b26f9_1001       conda-forge
    libcurl:          7.64.0-h541490c_2          conda-forge
    libdap4:          3.19.1-hd48c02d_1000       conda-forge
    libedit:          3.1.20170329-hf8c457e_1001 conda-forge
    libgdal:          2.2.4-he036fc0_8           conda-forge
    libgfortran:      3.0.0-1                    conda-forge
    libgfortran-ng:   7.2.0-hdf63c60_3           conda-forge
    libiconv:         1.15-h14c3975_1004         conda-forge
    libkml:           1.3.0-h328b03d_1009        conda-forge
    libnetcdf:        4.6.1-h628ed10_200         conda-forge
    libpng:           1.6.36-h84994c4_1000       conda-forge
    libpq:            11.2-h4770945_0            conda-forge
    libspatialindex:  1.8.5-hf484d3e_1003        conda-forge
    libspatialite:    4.3.0a-h9968ff2_1023       conda-forge
    libssh2:          1.8.0-h90d6eec_1004        conda-forge
    libtiff:          4.0.10-h648cc4a_1001       conda-forge
    libuuid:          2.32.1-h14c3975_1000       conda-forge
    libxcb:           1.13-h14c3975_1002         conda-forge
    libxml2:          2.9.8-h143f9aa_1005        conda-forge
    mapclassify:      2.0.1-py_0                 conda-forge
    matplotlib:       3.0.3-py36_0               conda-forge
    matplotlib-base:  3.0.3-py36h167e16e_0       conda-forge
    mkl:              2019.1-144                            
    mkl_fft:          1.0.10-py36h14c3975_1      conda-forge
    mkl_random:       1.0.2-py36h637b7d7_2       conda-forge
    munch:            2.3.2-py_0                 conda-forge
    numpy:            1.16.2-py36h7e9f1db_0                 
    numpy-base:       1.16.2-py36hde5b4d6_0                 
    openjpeg:         2.3.0-hf38bd82_1003        conda-forge
    pandas:           0.24.1-py36hf484d3e_0      conda-forge
    pcre:             8.42-h439df22_0                       
    pixman:           0.34.0-h14c3975_1003       conda-forge
    poppler:          0.67.0-h2fc8fa2_1002       conda-forge
    poppler-data:     0.4.9-1                    conda-forge
    proj4:            4.9.3-h470a237_8           conda-forge
    pthread-stubs:    0.4-h14c3975_1001          conda-forge
    pyparsing:        2.3.1-py_0                 conda-forge
    pyproj:           1.9.5.1-py36h2944ce7_1006  conda-forge
    pyqt:             5.6.0-py36h13b7fb3_1008    conda-forge
    python-dateutil:  2.8.0-py_0                 conda-forge
    pytz:             2018.9-py_0                conda-forge
    qt:               5.6.3-h8bf5577_3                      
    rtree:            0.8.3-py36_1000            conda-forge
    scipy:            1.2.1-py36h7c811a0_0                  
    shapely:          1.6.4-py36h0c48222_1000    conda-forge
    sip:              4.18.1-py36hf484d3e_1000   conda-forge
    six:              1.12.0-py36_1000           conda-forge
    tornado:          6.0.1-py36h14c3975_0       conda-forge
    xerces-c:         3.2.0-h5d6a6da_2           conda-forge
    xorg-kbproto:     1.0.7-h14c3975_1002        conda-forge
    xorg-libice:      1.0.9-h14c3975_1004        conda-forge
    xorg-libsm:       1.2.3-h4937e3b_1000        conda-forge
    xorg-libx11:      1.6.7-h14c3975_1000        conda-forge
    xorg-libxau:      1.0.9-h14c3975_0           conda-forge
    xorg-libxdmcp:    1.1.2-h14c3975_1007        conda-forge
    xorg-libxext:     1.3.3-h14c3975_1004        conda-forge
    xorg-libxrender:  0.9.10-h14c3975_1002       conda-forge
    xorg-renderproto: 0.11.1-h14c3975_1002       conda-forge
    xorg-xextproto:   7.3.0-h14c3975_1002        conda-forge
    xorg-xproto:      7.0.31-h14c3975_1007       conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
fontconfig-2.13.1    | 334 KB    | ####################################################################################################### | 100% 
cairo-1.14.12        | 1.4 MB    | ####################################################################################################### | 100% 
matplotlib-3.0.3     | 6 KB      | ####################################################################################################### | 100% 
libspatialite-4.3.0a | 3.1 MB    | ####################################################################################################### | 100% 
pthread-stubs-0.4    | 5 KB      | ####################################################################################################### | 100% 
libgdal-2.2.4        | 15.7 MB   | ####################################################################################################### | 100% 
numpy-1.16.2         | 49 KB     | ####################################################################################################### | 100% 
xorg-libsm-1.2.3     | 25 KB     | ####################################################################################################### | 100% 
blas-1.0             | 6 KB      | ####################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(geopandas_env) [USER@hpc-login-25 ~]$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.platform()
'Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core'
>>> import geopandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/home/USER/miniconda3/envs/geopandas_env/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/gpfs/home/USER/miniconda3/envs/geopandas_env/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/gpfs/home/USER/miniconda3/envs/geopandas_env/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/gpfs/home/USER/miniconda3/envs/geopandas_env/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /gpfs/home/USER/miniconda3/envs/geopandas_env/lib/python3.6/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs
```

**Comment by ocefpaf** [comment]
@jGaboardi in conda >=4.6 there is a new feature, that hopefully will became the default, that ensures the top channel will be used strictly unless a package does not exist on it. Try this:

```
conda config --set channel_priority strict  # the new feature
conda create --name geopandas_env python=3.6 geopandas --channel conda-forge --yes
conda activate geopandas_env
python -c "import geopandas; print(geopandas.__version__)"
0.4.1
```

**Comment by jGaboardi** [comment]
@ocefpaf This did the trick! Thanks so much for the quick response!
