### ISSUE TITLE
error while saving geodataframe as mapinfo .tab file

### ISSUE THREAD

**Issue by Manikandankasi01** [geopandas/geopandas#967]
Hi,

I'm getting below error while exporting geopandas dataframe as mapinfo .TAB file.

Code:

`import geopandas as gpd

p=r"D:\data.TAB"
testdata = gpd.read_file(p)
testdata.to_file("output.TAB", driver="MapInfo File")`

Traceback (most recent call last):
  File "fiona\ogrext.pyx", line 1167, in fiona.ogrext.WritingSession.start
  File "fiona\_err.pyx", line 246, in fiona._err.exc_wrap_int
fiona._err.CPLE_AppDefinedError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list fiel
d types.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    cable.to_file("output.TAB", driver="MapInfo File")
  File "C:\ProgramData\Anaconda3\lib\site-packages\geopandas\geodataframe.py", line 413, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\geopandas\io\file.py", line 116, in to_file
    schema=schema, **kwargs) as colxn:
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\env.py", line 397, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\__init__.py", line 267, in open
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 1173, in fiona.ogrext.WritingSession.start
fiona.errors.SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types
.

(base) D:\FTTC_Automation\Python\PC_Check\fttc_app>python test.py
Traceback (most recent call last):
  File "fiona\ogrext.pyx", line 1167, in fiona.ogrext.WritingSession.start
  File "fiona\_err.pyx", line 246, in fiona._err.exc_wrap_int
fiona._err.CPLE_AppDefinedError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list fiel
d types.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    cable.to_file("output.TAB", driver="MapInfo File")
  File "C:\ProgramData\Anaconda3\lib\site-packages\geopandas\geodataframe.py", line 413, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\geopandas\io\file.py", line 116, in to_file
    schema=schema, **kwargs) as colxn:
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\env.py", line 397, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\__init__.py", line 267, in open
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 1173, in fiona.ogrext.WritingSession.start
fiona.errors.SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types
.

Any help much appreciated.

Thanks in Advance,
Mani

**Comment by jorisvandenbossche** [comment]
Can you show the result of `df.head()` and `df.info()` ? (or ideally, provide a reproducible example) 
You get the error message *"Note that Mapinfo files don't support list field types"*. Do you have columns with lists?

**Comment by Manikandankasi01** [comment]
thanks for your quick response.
this is not a list. its a geodataframe.
PFA for df.head() & df.info results.

Thanks,
Mani
![df_head](https://user-images.githubusercontent.com/30194069/55772901-f2261400-5aab-11e9-9183-0d1d5c6426e5.PNG)
![df_info](https://user-images.githubusercontent.com/30194069/55772907-f5210480-5aab-11e9-83b7-0dcb9479b1ac.PNG)

**Comment by jorisvandenbossche** [comment]
> this is not a list. its a geodataframe.

What I mean is that the error message indicates is that one of the *columns of the GeoDataFrame* contains lists (so the values in one of columns), not that `df` itself is a list.

From the pasted image, we can't see all columns. Can you past the actual plain text version? (eg run it in an IPython console, that is easier to copy paster, or otherwise set `pd.options.display.notebook_repr_html = False`) 
Or even better, provide a reproducible code example that we can run and that reproduces the issue.

**Comment by Manikandankasi01** [comment]
Hi Jorisvan.

PFB for reproducible code.

`%matplotlib inline
from shapely.geometry import Point
from geopandas import datasets, GeoDataFrame, read_file
from geopandas.tools import overlay

# NYC Boros
zippath = datasets.get_path('nybb')
polydf = read_file(zippath)

# Generate some circles
b = [int(x) for x in polydf.total_bounds]
N = 10
polydf2 = GeoDataFrame([
    {'geometry': Point(x, y).buffer(10000), 'value1': x + y, 'value2': x - y}
    for x, y in zip(range(b[0], b[2], int((b[2] - b[0]) / N)),
                    range(b[1], b[3], int((b[3] - b[1]) / N)))])


polydf2.to_file("output.TAB", driver="MapInfo File")`

Thanks,
Mani

**Comment by jorisvandenbossche** [comment]
@Manikandankasi01 thanks for the reproducible example!

Indeed, I can also confirm that it gives that error. It actually also does that with the nybb dataset itself:

```
In [1]: import geopandas

In [2]: df = geopandas.read_file(geopandas.datasets.get_path('nybb'))

In [3]: df.to_file("test_output.TAB", driver="MapInfo File")
...
SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types. 

In [4]: geopandas.io.file.infer_schema(df)   
Out[4]: 
{'geometry': 'MultiPolygon',
 'properties': OrderedDict([('BoroCode', 'int'),
              ('BoroName', 'str'),
              ('Shape_Leng', 'float'),
              ('Shape_Area', 'float')])}
```

I am not familiar with the MapInfo file format, so I don't know if it has any limitations or specific requirements in usage (https://www.gdal.org/drv_mitab.html indeed mentions that list types are not supported). But at least it is a confusing error message, as there are no list types in the data (as also indicated by the inferred schema).

cc @sgillies

**Comment by jorisvandenbossche** [comment]
Although field type 12 should be int64? List of ints is field type 13?

**Comment by Manikandankasi01** [comment]
Thanks jorisvan for your response.

Actually I couldn't get the exception raised during mapinfo. Tab export. In my first example most of the columns are objects and few columns are float & int64. Even though columns in data frame are series then why it's throwing exceptions as list fields. 

I don't know what field 12 referancing.

Is there any work around for sort this issue?
Any help on this much appreciated. 

Thanks in advance, 
Mani

**Comment by jorisvandenbossche** [comment]
@Manikandankasi01 Sorry, I am not familiar enough with MapInfo to further help. You might want to raise an issue with `fiona`.

**Comment by Baron-K** [comment]
The issue was raised and close with fiona (https://github.com/Toblerity/Fiona/issues/748), so I will post my comment here as well.

I used the DataFrame constructor as indicated by a link by sgillies.

code:
`
import pandas as pd
import geopandas as gpd

df = pd.DataFrame({'Nbr': ['One', 'Two', 'Three'],
                     'Amt': [1, 2, 3],
                     'lat': [0.0, 0.0, 0.0],
                     'lon': [0.0, 0.0, 0.0]})

test = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.lon, df.lat))

test.to_file('G:/test.tab', driver='MapInfo File')
`
The above will error with:
Traceback (most recent call last):
  File "fiona\ogrext.pyx", line 1133, in fiona.ogrext.WritingSession.start
  File "fiona\_err.pyx", line 246, in fiona._err.exc_wrap_int
fiona._err.CPLE_AppDefinedError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Shared\Public\PyCharm\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Shared\Public\PyCharm\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Shared\Public\PyCharm\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Shared\Public\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/aa09070/.PyCharmCE2019.1/config/scratches/scratch_1.py", line 12, in <module>
    test.to_file('G:/test.tab', driver='MapInfo File')
  File "G:\GMpy\venv\lib\site-packages\geopandas\geodataframe.py", line 515, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "G:\GMpy\venv\lib\site-packages\geopandas\io\file.py", line 128, in to_file
    filename, "w", driver=driver, crs=df.crs, schema=schema, **kwargs
  File "G:\GMpy\venv\lib\site-packages\fiona\env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "G:\GMpy\venv\lib\site-packages\fiona\__init__.py", line 267, in open
    **kwargs)
  File "G:\GMpy\venv\lib\site-packages\fiona\collection.py", line 157, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 1139, in fiona.ogrext.WritingSession.start
fiona.errors.SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types. 

However, if I change the Amt values to float, i.e 1.0, 2.0, 3.0 (or even just change 1 of the values to float), it does not error when writing the MapInfo File.
 New code:
df = pd.DataFrame({'Nbr': ['One', 'Two', 'Three'],
                     'Amt': [**1.0**, 2, 3],
                     'lat': [0.0, 0.0, 0.0],
                     'lon': [0.0, 0.0, 0.0]})

Hope this helps.

**Comment by matthewsheeran** [comment]
Its a bug or mis-informative error (using my port of ogr2ogr.c to C#).
I've upgraded NuGet Gdal + Gdal.Native + Gdal.Plugins form 1.11.1 through 2.4.2 (where I first saw the bug) to 2.4.4 which broke my working test.

Using OSGeo4W64 produces the follow warning rather than error so I guess I will heed it and change my test data:
"ogr2ogr -f "MapInfo File" tmp.tab test.shp -overwrite
Warning 1: The output driver does not seem to natively support Integer64 type for field STATESP020. Converting it to Real instead. -mapFieldType can be used to control field type conversion."

**Comment by PeterFogh** [comment]
I have also encountered this error of saving integer columns to .TAB files with the MapInfo driver.

I found out that all integer types (int64, int32, and int16) results in the error "CPLE_AppDefinedError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types."

![geopandas cannot save int to tab file](https://user-images.githubusercontent.com/5435299/95985758-42123380-0e25-11eb-8417-7ddfceb00e89.png)

Currently, I use the workaround by casting the integer columns to floats.

**Comment by adambasile** [comment]
Here's workaround if you want to write ints as ints
```
schema = gpd.io.file.infer_schema(gdf) # ordinarily this is inferred within gpd.to_file()
for col, dtype in schema["properties"].items():
    if dtype == "int" or dtype == "int64":
        schema["properties"][col] = "int32"
gdf.to_file("output.tab", driver="MapInfo File", schema=schema)
```

**Comment by jorisvandenbossche** [comment]
We should probably update GeoPandas' `infer_schema` to ensure that if you have "int32" columns, we also use "int32" instead of the generic "int". 
(to ensure you could do `gdf["col"] = gdf["col"].astype("int32")` as workaround instead)

**Comment by jadebel** [comment]
Hi is this issue still open?

**Comment by martinfleis** [comment]
@jadebel Yes, the suggestion @jorisvandenbossche made above still needs to be done.

**Comment by jadebel** [comment]
@martinfleis Can you assign this to me?

**Comment by martinfleis** [comment]
I can't do it technically as you're not a member of the organisation but let's assume I did. 

Thanks!

**Comment by Verdarias** [comment]
Hello I am working with @jadebel on this issue. I have two questions. Aside from int32 are there any other data types we need to support? Also, how do we run the test suites (test_file.py)?

**Comment by martinfleis** [comment]
> Aside from int32 are there any other data types we need to support?

@Verdarias You will have to check that. I am not familiar enough with mapinfo tab to say that. I'd suggest checking what it supports and getting from there.

> Also, how do we run the test suites (test_file.py)

We use `pytest` to run our tests. Assuming you have a [development environment](https://geopandas.org/en/stable/community/contributing.html#creating-a-development-environment) you can navigate to the folder with `test_file.py` and run

```
pytest test_file.py
```

**Comment by jadebel** [comment]
Just to clarify: we are updating infer_schema so that in all cases (not just in the cases when the driver is "MapInfo File") if we have an int32 column, we use int32 overall, right?

**Comment by martinfleis** [comment]
That sounds reasonable, though I am not sure if all formats will be happy about that. It needs to be tested.

**Comment by jadebel** [comment]
I have submitted a pull request, but for some reason it is failing the linting test despite running the required functions in the style guide in the development environment document. Do you know what is going on?

**Comment by XVINILX** [comment]
This issue shouldn't be closed?

**Comment by martinfleis** [comment]
Closed by [#2950](https://github.com/geopandas/geopandas/pull/2950).
